### ISSUE TITLE
All the select input with classes, highlight V and E classes

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#101]
V and E play an important role in OrientDB. In all the select V and E should be the first 2 classes, then a separator and all the others. Example:

```
V (vertex)
E (edge)
------------
OUser
ORole
OIdentity
....
```

**Comment by maggiolo00** [comment]
Hi guys i think this is covered by the Schema rework https://github.com/orientechnologies/orientdb-studio/issues/431

Can we close this?

**Comment by lvca** [comment]
Already done.
