### ISSUE TITLE
Aborting an Index-building should also abort the process in the console

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#110]
Well creating an index, especially on FULLTEXT can take some hours. And if you hit "Abort" it does not really abort it, it just closes the pop-up window.

Is this intended? And if you CTRL-C in the console the server is shut down. Is this also intended? I'm just not sure, if that's fine, everything is cool =)

Priority: low

**Comment by lvca** [comment]
Confirm: CTRL+C stop it softly.
