### ISSUE TITLE
Versioning of function code and their diff in studio

### ISSUE THREAD

**Issue by gauravdhiman** [orientechnologies/orientdb-studio#144]
As writing functions in Studio is like writing code in IDE, it will be good to maintain the versions of function codes so that we can revert back to older versions of function, if required.

It will be great if one can also see the diff between two selected versions of function code. To check how it works, check Wordpress. Wordpress CMS can maintian older versions of page / post content and one can revert back to any older version + editor can see the difference between two versions of content.

**Comment by lvca** [comment]
Not relevant anymore, closing it.
