### ISSUE TITLE
Graph Editor: Saving configuration doesn't persist

### ISSUE THREAD

**Issue by shadoi** [orientechnologies/orientdb-studio#160]
If you modify the display properties of a vertex, and then save the configuration, it should reload those properties when you view that vertex again.  Currently it seems either what the display properties are, or they are not being re-loaded properly.

**Comment by iforwms** [comment]
Any progress on this? Any way of maybe implementing a CSS-esque format similar to Neo4j?

**Comment by lvca** [comment]
@iforwms Could you open a new issue about that? Please specify also what you'd like to have

**Comment by jetheurer** [comment]
Can the configurations be written into code?

**Comment by JeroenSteen** [comment]
I have the same issue in Studio version 2.1, when I change the display, fill and stroke and press "Save configuration" I see: "Configuration Saved Correctly". But when I come back (switching between tabs and perform the query again), I don't see the display, fill and stroke that I have chosen.

**Comment by maggiolo00** [comment]
hi @JeroenSteen 

were you logged as with root or admin ?

**Comment by JeroenSteen** [comment]
@maggiolo00 I was logged in as root user in the Studio.

**Comment by maggiolo00** [comment]
Try with admin should work.

**Comment by maggiolo00** [comment]
There is an open issue to inform that some ops are not enabled with root

https://github.com/orientechnologies/orientdb-studio/issues/326

**Comment by JeroenSteen** [comment]
@maggiolo00 I now added a admin user in the xml config (/opt/orientdb/config/orientdb-server-config.xml), like so:

<users>
	<user resources="*" password="my_pass" name="admin"/>
</users>

And then I stopped and started the orientdb service. I can now log in to the Studio for the admin user, but it still doesn't remembers my configurations.

**Comment by migpics** [comment]
I am having this same issue with
Studio version : 2.1
OrientDB version : 2.1.3
Anyone else find a resolution to this?

**Comment by migpics** [comment]
Just tried the admin approach and am still having the same issue.

**Comment by sagarmaniar** [comment]
@iforwms @lvca @maggiolo00 Even with the admin login the session is lost on the refresh of the studio in the browser. Hence the saved configurations are not reflected after a browser refresh when logged in as a admin or as any other user. Could you please help me out with this issue?

**Comment by migpics** [comment]
So Iike JeroenSteen  I added a user named admin to the database with my own password.
This still did not work.
When I removed the admin user from the list and used the default login of user:  admin and password: admin, then the configuration persisted.
So I'm not sure if this is a bug but I wanted to share with you my results.

**Comment by andrea-ligios** [comment]
As said, THE WORKAROUND IS TO USE A DIFFERENT USER. 
Just create a user with all the roles (ADMIN, READER, WRITER) and the configuration will be saved and persisted correctly. 
I don't know which role is fine and which one cause problems, just sharing a way that immediately works, while waiting for the fix (#326).

**Comment by baloooo** [comment]
I can verify that creating a new user with the role ADMIN solves the issue in OrientDB Server v3.0.2
