### ISSUE TITLE
Saving changes to display on graph produces multiple notices

### ISSUE THREAD

**Issue by mccarvell** [orientechnologies/orientdb-studio#182]
If I am in graph view and click the eye icon of a node, then change the display value and click "Save Configuration"... I get the success notice 5 times stacked on top of each other for a brief moment.
![screen shot 2014-10-24 at 2 09 43 am](https://cloud.githubusercontent.com/assets/2651311/4765767/670b8136-5b44-11e4-9163-6c3e75abef70.png)

**Comment by maggiolo00** [comment]
@mccarvell have you tried with orientdb-rc2 ?

**Comment by lvca** [comment]
@mccarvell do you still see this problem? I'm closing it, in case please re-comment it.
