### ISSUE TITLE
Creating Classes should also get an Advanced Mode

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#198]
Current Creating a Class is like
http://i.imgur.com/N8bSQyr.png

Should more be like the current DB Creating
http://i.imgur.com/fGIuIPq.png (like the red area)

I mean for Creating Properties and Indexes it's fine. Here is no need to not show min, max and so on. This is kind of always important.

But simply noone is using **Abstract** or **Alias**, so this should also be optional via Advanced Mode.

WDYT?

**Comment by lvca** [comment]
Not relevant anymore, closing it.
