### ISSUE TITLE
Using D3 for Directed Graph Editor

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#2]
I found this link that's pretty interesting:

http://bl.ocks.org/rkirsling/5001347

We could write a new tab for Studio where graphs could be also edited. WDYT?

**Comment by tim-hari** [comment]
> orientdb-studio.wiki/Graph-Editor.html
Hi,

http://www.orientechnologies.com/docs/last/orientdb-studio.wiki/Graph-Editor.html
The link seems to be broken, I'm trying to visualize a network graph within angular. Instead of using orient DB graph editor, are there similar graph templates that can be reused in angular?
