### ISSUE TITLE
2.0-M3 studio no longer remembers queries when switching between tabs

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb-studio#205]
For example, use the "Browse" tab to execute a few queries, the click on the "Schema" tab, the click back on the "Browse" tab and all queries are gone.  Previous versions of Studio (snapshots after 2.0-M2) remembered the queries when switching between tabs, and that was a very useful feature.

**Comment by lvca** [comment]
This isn't supported: you should be authenticated with a valid db user to use this feature.
