### ISSUE TITLE
Graph Editor: re-size graph area to better use the space available in the page

### ISSUE THREAD

**Issue by fabriziofortino** [orientechnologies/orientdb-studio#208]
The graph area should be re-sized according to the space available in the page. As you can see from the attached screenshot about 30% of the page remains empty.

![image](https://cloud.githubusercontent.com/assets/1469849/5215821/2de73a22-7623-11e4-91c6-1314830bd6a8.png)

**Comment by maggiolo00** [comment]
@fabriziofortino  Fixed in 2.2.x
