### ISSUE TITLE
Split Schema panel in 3 areas

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#21]
- Vertex classes
- Edge classes
- Other classes

This simplify the understanding of what is a vertex, and what is an edge

**Comment by santo-it** [comment]
Hi, I had the very same idea. I noticed this enhancement is quite old so I am commenting just to say that this is still current. I believe it's important if this is implemented, especially from a usability and easiness-of-use point of view. A label like "System Classes" could probably be used for the "other" classes. Classes like OSchedule, OUser, OSequence, etc are not intuitive and may cause confusion to new users. Suppose user has a vertex class named "Style".  When they load the tab "Schema" right now the "Style" class is shown on page two, after the system classes. If instead custom and system classes are kept separated, the "Style" class would immediately be visible on the first page as users may expect (assuming user has just a few custom classes). Thanks

**Comment by maggiolo00** [comment]
Hi @santo-it 
i've pushed the implementation. It should be available in the next snapshot.
I've mark this as resolved instead of closing directly as it's a major change and could require
a feedback before closing 

Same for
https://github.com/orientechnologies/orientdb-studio/issues/431

Thanks

**Comment by maggiolo00** [comment]
@santo-it 
i've checked the latest studio is pushed on sonatype. 

If you build orientdb from the latest source 2.2.x you are able to try the new Schema Manager

Thanks

**Comment by santo-it** [comment]
Thanks @maggiolo00,

Closing.
