### ISSUE TITLE
2.0-rc1: studio shows wrong lightweight edges status

### ISSUE THREAD

**Issue by 8forty** [orientechnologies/orientdb-studio#220]
After creating a new database without setting any properties, I looked at the DB section "Configuration" tab and the custom property "useLightweightEdges" has a checkmark in the box, but running a test program shows that heavy edges are in fact used.

**Comment by maggiolo00** [comment]
@8forty how did you create the database?

**Comment by 8forty** [comment]
From the console: "create database remote:localhost/tesetdb root root plocal"

**Comment by 8forty** [comment]
FYI this also happens in 2.0-rc2.
