### ISSUE TITLE
DROP PROPERTY not working

### ISSUE THREAD

**Issue by mvincellette** [orientechnologies/orientdb-studio#222]
We're using version: orientdb-community-2.0-20150110.091050-529-distribution

Our ***User*** class was created as follows:
* CREATE CLASS User EXTENDS V
* ALTER CLASS User STRICTMODE TRUE

There are about 1,300 vertices in ***User***.

If I issue a **DROP PROPERTY User.profilePhotoId** command through the "Browse" tab in the web portal, it shows that the command executed successfully, but if I then issue **SELECT FROM User**, the property is still displayed.

If I switch to the "Schema" tab, though, and double-click the ***User*** class, the property is gone.

**Comment by lvca** [comment]
Schema property and content are not like in RDBMS: you can drop a property without changing the database content. We'd like to introduce some new keywords to specify to update also the DB by removing the property content.

However now you should do also:

    update User remove profilePhotoId

**Comment by mvincellette** [comment]
Thanks for the feedback. I had though that might be the case but assumed setting **STRICTMODE** to **true** would have prevented that.

Not a problem. Thanks for a great product!
