### ISSUE TITLE
wrong index engine

### ISSUE THREAD

**Issue by micha-nerdlichter** [orientechnologies/orientdb-studio#223]
I created an Index of type "UNIQUE_HASH_INDEX" and studio assigns the "SBTREE" engine. Shouldn't this be "HASH"?

![image](https://cloud.githubusercontent.com/assets/8459594/5738588/5712362c-9bee-11e4-8ef0-9a9d29b21759.png)

**Comment by lvca** [comment]
The information retrieved is wrong, but "engine" field is never used. So I'm going to put this priority lower.

**Comment by santo-it** [comment]
Hi @micha-nerdlichter ,

Thank you for submitting this issue. I have tried this with the latest 2.2.14 version, and it seems I cannot repeat it:

![index_cant_repeat](https://cloud.githubusercontent.com/assets/14923389/21595343/4f65f08c-d12d-11e6-83bf-9833101205d5.PNG)

Thinking to close this, unless you are still affected?

Thanks,
