### ISSUE TITLE
Cluster counter is wrong?

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb-studio#227]
When creating a class in studio, I was used to be returned id of the cluster of that class.

After creating a database, I can see that the last cluster id used is 11.
Then:

```sql
create class AbstractClass ABSTRACT # (returns 12 but it's -1)
create class ConcreteClass # (returns 13 but it's 12)
# and so on...
```

It's nothing major and it should be easy to fix.

**Comment by kwoxer** [comment]
So the popup says the cluster value?

**Comment by vitorenesduarte** [comment]
I wouldn't call it a popup. I think every successful command in studio returns a JSON.
In this case, these are the two JSON retrieved:
```json
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": 12
        }
    ],
    "notification": "Query executed in 0.08 sec. Returned 1 record(s)"
}
```

```json
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": 13
        }
    ],
    "notification": "Query executed in 0.138 sec. Returned 1 record(s)"
}
```

**Comment by lvca** [comment]
create class returns the class number in database, not the clusters.
