### ISSUE TITLE
QUERY ALL button open in new tab

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#231]
I'm just asking if it would be possible that the buttons in Studio are available via Mousewheel click or at least rightclick and open in new tab?

http://i.imgur.com/rk1nEqa.png

I think this would be good because currently just clicking is available and then I'm in Browse instead of staying in Schema.

Prio: low

**Comment by lvca** [comment]
Not relevant anymore, closing it.
