### ISSUE TITLE
Unable to remove property from class - OSchemaException: Property not found in class

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#233]
http://i.imgur.com/ohVt2UM.png

I was playing a bit around. For sure I could drop the class now and recreate it. But I would like to know what else I could do.

**Comment by maggiolo00** [comment]
How to reproduce that?

**Comment by kwoxer** [comment]
Too long ago, but tried it very often and always the same.

**Comment by santo-it** [comment]
Thanks for opening this issue. Closing as we cannot repeat it. In case this happens again with latest Studio version please feel free to reopen

Thanks,
