### ISSUE TITLE
After creating index the engine column is empty

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#235]
http://i.imgur.com/kXxJSdh.png

Just helping a reload to fill it with the engine. Is this intended. I mean there is no reason from my perspective.

prio: middle

**Comment by alexspirtmsu** [comment]
I notice this too. And Engine type is still wrong. For example: studio shows SBTREE for UNIQUE_HASH_INDEX.

**Comment by vinaySimility** [comment]
Yeah Engine type is being displayed wrong. I don't know whether its actually using "HashIndex" algorithm or not.

**Comment by maggiolo00** [comment]
Fixed.
See here
https://github.com/orientechnologies/orientdb/issues/4983
