### ISSUE TITLE
Lucene search does not find any result somehow

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#236]
I have some experience with Lucene so far. Today I started with the new Version 2.0.1.

I created a class and a property and then set the Lucene Fulltext on it. 

But somehow I'm not able to get it working. There is definitly an entry in that class:
**http://i.imgur.com/EmHU606.png**

But on the Lucene query you see that it's empty. Here the class and index:
**http://i.imgur.com/ke0RfeS.png**

So for what reason it is empty? I mean is there something broken in the new version, or did anything change? I mean the same stuff here worked in 2.0 M2. 

I'm a bit confused.

Btw: also tested on V class with Lucene on name property. Same result. If there is something changed, please edit those pages: https://github.com/orientechnologies/orientdb-lucene/wiki/Full-Text-Index

Sure I could simply use the usual Index Engine. But I really like Lucene and want to use it =)

Thank you guys.

**Comment by santo-it** [comment]
Hi,

Thanks for opening this issue. I am not able to repeat it with latest version 2.2.15
I'm closing this. If you experience the problem again, please feel free to reopen

Thanks again,
