### ISSUE TITLE
Changing property type often has no effect

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#237]
http://i.imgur.com/dPeEMXO.png

I don't know but the other things are changed by hitting the **Save** button.

Changing the **Type** and then hitting Save does not properly save it all the time. Sometimes I have to click a few times and often it does not work. 

Even tho it cannot be converted from String to let's say any data type that does not fit. But I for instance took double and float and also had the same issue.

It's also not a visual bug in terms of missing popup box. It really does not change the type.

prio: high

**Comment by maggiolo00** [comment]
Should be resolved with this
https://github.com/orientechnologies/orientdb-studio/issues/191

**Comment by maggiolo00** [comment]
I'm closing this as the fix of 4 months ago should solve it.
In case reopen it

**Comment by kwoxer** [comment]
Didn't test yet, but still on my todo list =) but I'm also sure it is already fixed. Thx.
