### ISSUE TITLE
GraphEditor not drawing more than 1 edge with the same class name

### ISSUE THREAD

**Issue by josegomezr** [orientechnologies/orientdb-studio#240]
Consider the following data

![Table Data](http://i.imgur.com/BJXBqw4.png)

There are 2 edges type E but only the first one created is displayed on Graph

![Graph](http://i.imgur.com/1zaGLRB.png)

**Comment by santo-it** [comment]
Hi @josegomezr ,

Many thanks for opening this issue. We fixed this in the latest release of OrientDB (2.2.14) (This is the issue that we closed: https://github.com/orientechnologies/orientdb/issues/6900)

Please let us know if we can close this issue now

Thanks,

**Comment by santo-it** [comment]
Hi,

Going ahead and closing this issue now - please feel free to reopen it if anything

Thanks!
