### ISSUE TITLE
Spring Data for OrientDB

### ISSUE THREAD

**Issue by Archana14** [orientechnologies/orientdb-studio#241]
Hi 
I want to use Spring Data for OrientDB. But it seems its in a implementation Phase. It will be good to have Spring data for OrientDB. Could please let me know when it will available or Could you suggest best option other than Spring data.

**Comment by Archana14** [comment]
I am using Graph database in my Application. Please let me know which will be the best option other than Spring data.

**Comment by Archana14** [comment]
Moving this issue to spring data orient

**Comment by lvca** [comment]
OrientDB is written in Java, so you can use it directly without Spring.
