### ISSUE TITLE
Reader Role Continuous execution of script

### ISSUE THREAD

**Issue by mshettysubbaiah** [orientechnologies/orientdb-studio#242]
Logged in using admin admin into the VehiclesHistoryGraph
Clicked on Security --> Roles --> Name = "reader"
The application enters into the recursive mode and warns with unresponsive script. The warning messages show debug, stop or continue. I had to enter into debug mode and close the browser. I used Fireforx 35.0.1 browser on Mac OSX 10.10.2

![screen shot 2015-02-23 at 5 17 06 pm](https://cloud.githubusercontent.com/assets/5303969/6339915/da490f92-bb7f-11e4-9471-2f4c3207c8ce.png)

**Comment by lvca** [comment]
OrientDB version?

**Comment by mshettysubbaiah** [comment]
2.0.3 Community Edition was used

**Comment by lvca** [comment]
is it possible you created the db with OrientDB 2.0-Mx?

**Comment by mshettysubbaiah** [comment]
Luca,

Thanks for following up on this. I restarted the server and unable to reproduce. I will watch this and report it when I find. We can close it. 

regards,
Manjunath

**Comment by lvca** [comment]
Great.
