### ISSUE TITLE
Query history even if you close orientdb studio

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb-studio#245]
Hi, I don't know if someone has requested that. It would be nice if you close the query-builder and be able to have the history of the queries for that database by pressing Ctrl+ Down/Up or Up/Down arrows or something like that. Neo4j visualization tool provides that and it is really handy. Thanks

**Comment by maggiolo00** [comment]
hi @zifnab87, do you mean for graph view?

**Comment by zifnab87** [comment]
I mean for both. I should be able to even close the browser or even the server and be able to access the whole history of the queries for that database (just the commands not the results).. This is possible in Neo4j visualization tool. I assume there is some logging for the queries that run against the server.

**Comment by ljantzen** [comment]
You could just put the queries in the persisten local-storage of the browser

**Comment by zifnab87** [comment]
Also what about

**Comment by maggiolo00** [comment]
We store queries in localstorage and show history. We only miss the Ctrl+ Down/Up or Up/Down arrows

**Comment by zifnab87** [comment]
Sorry I closed/reopened it by mistake :) I saw that queries seem to be sticking around - thanks for that :) I am waiting for the navigation up/down . I decided to open new issue for my comment

**Comment by maggiolo00** [comment]
ok :D

**Comment by ropeladder** [comment]
I just installed 2.1 RC4 (up from 2.0) and the Browse page stopped saving any of my queries in Firefox, even if I just switch over to a different page (e.g. Schema). IE 11 seems to work.

**Comment by lvca** [comment]
This is already working with 2.2.7 and major.
