### ISSUE TITLE
Graph Editor - Plug-in support for server side functions

### ISSUE THREAD

**Issue by rajohn96** [orientechnologies/orientdb-studio#249]
Has anyone considered the desire to add access to server side functions from the admin graph ui? For instance, while now a user can add/delete edges, vertices, and properties from the studio graph ui, there might be cases in which a user would want to operate on a chosen edge, vertex or set of either/both (which would necessitate the ability to select more than one edge and/or vertex at a time of course), with that operation being handled via a server side function. What do you think? Is there a plug-in interface being contemplated for these sorts of things? Or, have I just missed it?

Thanks!

Alan

**Comment by lvca** [comment]
Can you elaborate it more? We already offer the ability to crete functions and execute them from studio.

**Comment by rajohn96** [comment]
yes, i agree, we can execute functions from the CLI, but what I am describing is the ability to do so from the graph UI (specifically, the menu that wraps a vertex when selected). As an example, for the OSERAF initiative (https://groups.google.com/forum/#!forum/oseraf), we have three functions that are specifically driven from this sort of interaction, resolve, split and merge; right now these are enable from a purpose built UI, which lacks some of the basic graph functions that Studio already has. As describe, Resolve would take a given vertex and its properties and traverse the balance or the graph (or some subset) and identity other vertices which it "matches" (from a property value POV), allowing the user to then "Merge" these, which, as a by product, would create a third vertex with links to the two (or more) vertices that were resolved. Join does this explicit, and Split does the reverse. All of these can be expressed as server side functions, and ideally we could initiate these sorts of functions (along with applicable context) from the UI, the same way we can initiate basic editing functions, or egograph functions, as is now the case. I can imagine others might have similar behaviors they would like to see initiated in a similar manner, either from single vertex selection, single edge selection or multiple/subgraph selection. To have this accessible as a plug-in would make this sort of develop much more palatable, making Studio able to be used as more of an analytic tool vs administrative tool going forward.

Does this make sense?

**Comment by rajohn96** [comment]
Any thoughts on this one yet?

**Comment by lvca** [comment]
If I understood correctly, you'd like having a sort of "methods" associated to the classes, invocable from Studio, right? 

We could support pluggable stuff in Studio, but please let us know the exact point where you would like to extend pages.

**Comment by rajohn96** [comment]
I think its easier than this; when you click a vertex in the studio it is enlarged and surrounded by a set of actions, like edit the attributes for the vertex, follow the links in, follow the links out, etc. I am just suggesting that another action/set of action might be to call a server side function, with the vertex id (at the very least) as the argument, and then that function might either simply execute, or (depending on its nature) may take focus on prompt the user for additional data before executing (as is done now with the edit action). Basically, make these behaviors somewhat/completely pluggable, so the studio could serve in some regards as an IDE of sorts for the graph, when coupled with customer client side or server side logic. 

Does this make sense?

**Comment by lvca** [comment]
No more relevant, closing it.
