### ISSUE TITLE
Can't import public database

### ISSUE THREAD

**Issue by marmax** [orientechnologies/orientdb-studio#251]
I am not able to import sample database - VehicleHistoryGraph:

java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.orientechnologies.com/public-databases/VehicleHistoryGraph.zip

If I try the given url in any browser, it gets me to the file.

I bet the problem lies in request headers, especially in 'User-Agent: Java/1.8.0_40'

**Comment by Dethblo** [comment]
I'm seeing the same behavior.  I also tried restoring the VehicleHistoryGraph.zip database using the console:

> create database remote:localhost/VehicleHistoryGraph root password plocal
> restore database d:/temp3/VehicleHistoryGraph.zip

I get the following error:

Restoring database database d:/temp3/VehicleHistoryGraph.zip...
Error: java.lang.UnsupportedOperationException: restore

Any thoughts?

**Comment by lvca** [comment]
restore doesn't work with `remote:`. Use plocal instead

**Comment by ljantzen** [comment]
I dont think this issue should be closed, as I can reproduce it with the following steps.

1) Start with a pc with just java installed. 
2) Download and extract orientdb-community-2.0.8.zip 
3) Start bin/server.sh and enter new root password
4) Launch localhost:2480 and go to cloud import
5) try to import any of the databases listed, they all say import failed, 403. 

Going directly to the url for the zip returns the file, so this surely is an error in Studio? 

![cloudimport-fail](https://cloud.githubusercontent.com/assets/67438/7581860/2f956fe6-f888-11e4-96ef-4a8ec1b13443.png)

**Comment by MichaelRoders** [comment]
I have the exact same issue with the latest 2.1 RC on Mac OSX.

**Comment by lvca** [comment]
This has ben fixed by: https://github.com/orientechnologies/orientdb/commit/177d62d9cf56e5ff3ee50aa46f7fe80eff4e8950. So my fault: it's not invalid, it was a bug (the HTTP request had no agent). However I'm trying to change the .htaccess on orientdb.com website to support no-agent requests and let older OrientDB Studio to work.

**Comment by ljantzen** [comment]
Excellent.  Thank you.

**Comment by lvca** [comment]
Trying with curl (with no agent) seems to work:
```
curl -A "" -v http://orientdb.com/public-databases/OpenBeer.zip > test.zip
```

But Studio receives 304. Any apache expert here?

**Comment by MichaelRoders** [comment]
Now the first try returns the 403 and the second states that the database already exists (but does not).

> com.orientechnologies.orient.core.exception.ODatabaseException: Database named 'VehicleHistoryGraph' already exists

Meanwhile there was a 500 Internal Server Error:

![internalservererror](https://cloud.githubusercontent.com/assets/10655678/7587474/c75e185e-f8b6-11e4-9dec-60d566d3f13a.png)

**Comment by lvca** [comment]
Last 2.1-SNAPSHOT already fixes this. I'd like to fix this problem with old releases, but Studio continues to get a 403 even if using curl with no agent (the exact same request) works.

**Comment by ljantzen** [comment]
Could it be a CORS issue? http://enable-cors.org/

**Comment by lvca** [comment]
Guys, is this working now?

**Comment by hyunjun** [comment]
1st day to practice orientDB v2.0.10, and I did like below. I'm not sure whether I did right, however I can see records from cluster:Make (not Make like in the tutorial https://www.udemy.com/orientdb-getting-started/?dtcode=IPAxZyS314XL#/lecture/1783078)
```
$ wget http://www.orientechnologies.com/public-databases/VehicleHistoryGraph.zip
$ ./console.sh
orientdb> create database plocal:../databases/VehicleHistoryGraph admin admin plocal
orientdb {db=VehicleHistoryGraph}> restore database VehicleHistoryGraph.zip
orientdb {db=VehicleHistoryGraph}> disconnect
orientdb> connect remote:10.15.86.143/VehicleHistoryGraph admin admin
orientdb {db=VehicleHistoryGraph}> select from cluster:Make

----+-------+------+-------------+---------+---------
#   |@RID   |@CLASS|name         |in_isMake|out_Sold
----+-------+------+-------------+---------+---------
0   |#15:606|null  |Plymouth     |[size=9] |[size=4]
1   |#15:607|null  |Ford         |[size=-1]|[size=21]
2   |#15:608|null  |Mercedes-Benz|[size=24]|[size=11]
3   |#15:609|null  |BMW          |[size=30]|[size=8]
4   |#15:610|null  |Mitsubishi   |[size=17]|[size=8]
5   |#15:611|null  |Eagle        |[size=4] |[size=2]
6   |#15:612|null  |Kia          |[size=4] |[size=3]
7   |#15:613|null  |Audi         |[size=5] |null
8   |#15:614|null  |Volkswagen   |[size=15]|[size=11]
9   |#15:615|null  |Nissan       |[size=19]|[size=6]
10  |#15:616|null  |Dodge        |[size=34]|[size=12]
11  |#15:617|null  |Pontiac      |[size=12]|[size=2]
12  |#15:618|null  |Jaguar       |[size=7] |[size=4]
13  |#15:619|null  |Chevrolet    |[size=-1]|[size=19]
14  |#15:620|null  |Volvo        |[size=11]|[size=4]
15  |#15:621|null  |Subaru       |[size=16]|[size=7]
16  |#15:622|null  |Hyundai      |[size=7] |[size=4]
17  |#15:623|null  |Cadillac     |[size=2] |null
18  |#15:624|null  |Suzuki       |[size=6] |[size=3]
19  |#15:625|null  |Mercury      |[size=12]|[size=5]
----+-------+------+-------------+---------+---------
LIMIT EXCEEDED: resultset contains more items not displayed (limit=20)

20 item(s) found. Query executed in 0.009 sec(s).
```
