### ISSUE TITLE
Graph view - Display settings Config

### ISSUE THREAD

**Issue by iforwms** [orientechnologies/orientdb-studio#254]
Changing display settings in Graph view does not persist within a session. Suggest each database has an associated CSS or pseudo-CSS file which handles the display of vertices and edges.

Vertex/Edge class could be used as a CSS class selector, but with custom variables such as radius and which property to display. This file could be manually edited, or updated automatically from within the Graph view.

**Comment by lvca** [comment]
Tried and works. What version are you using? Did you click on Save configuration button?

**Comment by iforwms** [comment]
Here are screenshots of each step. First switch to the graph section and get all Edges (I also clicked on each node as I'm sure I read the 'dimmed' nodes have only their RID's loadded. 

I then applied some basic styling and changed the vertex label. Saves in the sidebar, then clicked the Save button near the query bar, switch back to the browse section, then back to the graph view and searched for all vertices. As you can see all styles have been reset.

According to the about page I'm running:
Studio version : 2.0
OrientDB version : 2.0.6

![01 small](https://cloud.githubusercontent.com/assets/10304616/7082398/4df9f63e-df86-11e4-881a-ba9beded2e89.png)
![02 small](https://cloud.githubusercontent.com/assets/10304616/7082399/4dfa58a4-df86-11e4-9041-2f58b3691e72.png)
![03 small](https://cloud.githubusercontent.com/assets/10304616/7082402/4dfda856-df86-11e4-9dd6-2cc999aa91f9.png)
![04 small](https://cloud.githubusercontent.com/assets/10304616/7082400/4dfcd78c-df86-11e4-9ea0-277a15047eac.png)
![05 small](https://cloud.githubusercontent.com/assets/10304616/7082401/4dfd3a60-df86-11e4-8c08-43c62930594f.png)
![06 small](https://cloud.githubusercontent.com/assets/10304616/7082403/4e04283e-df86-11e4-944a-21c64424e599.png)

**Comment by alphaGeekWarrior** [comment]
I am having a lot of similar issues. The documentation on the configuration of the graph viewer. How do we reset config? When I save a config in a database, it seems to stick to other database such as concert for dead database.

**Comment by oharlem** [comment]
Same issue. Would be great to persist styling as part of/as related info to the db.

**Comment by dopgm** [comment]
Same issue. Would be great to persist styling as part of/as related info to the db.

**Comment by maggiolo00** [comment]
@iforwms  i see that you connect to the database with root users that means that your configuration will not be saved correctly.

Can you try with admin user?

**Comment by sagarmaniar** [comment]
@iforwms @lvca Even with the admin login the session is lost on the refresh of the studio in the browser. Hence the saved configurations are not reflected after a browser refresh when logged in as a admin or as any other user. Could you please help me out with this issue?

**Comment by maggiolo00** [comment]
@sagarmaniar 

can you post a screenshot?

**Comment by santo-it** [comment]
Hi all,

I am not able to repeat this with 2.2.15. I tried several combinations, changing colors, vertex sizes and labels, using different browsers. It seems the changes are per-database and persistent, as expected

If you notice this again, please provide the steps to reproduce

I agree about the need to provide a way to reset configuration

@maggiolo00 about root user: I understand configuration won't work for root user. If you explain more I'll document the limitation

Thanks,

**Comment by santo-it** [comment]
Hi. Closing as per my previous comment. Please reopen if needed. Thanks,

**Comment by janosmathe** [comment]
Recognizing that I am fairly late to the discussion, I wanted to offer a potential resolution.
* Use an account local to the database (e.g. admin) when saving configuration, as the settings get recorded on a per user level.
* When using root, configuration options seemingly are saved, but after a refresh the settings are lost.
