### ISSUE TITLE
Wrong link - easy fix

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb-studio#255]
Here
![screen shot 2015-04-14 at 17 08 01](https://cloud.githubusercontent.com/assets/4520516/7141348/ee73d9fa-e2c8-11e4-8cd7-7e580ba4dfe7.png)
Clusters links to [this](http://orientdb.com/docs/2.0/orientdb.wiki/Clusters.html).

This seems to be the old documentation.

**Comment by lvca** [comment]
The link is correct. Why is old?

**Comment by vitorenesduarte** [comment]
I'm used to see all links pointing to:
`http://orientdb.com/docs/last/...`
and in that case we have:
`http://orientdb.com/docs/2.0/...`

**Comment by lvca** [comment]
The reason is about the Studio version: 2.0, so it points to that documentation to be versioned.
