### ISSUE TITLE
Fail to create a database from the cloud in studio

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb-studio#256]
Studio fail to download and upload the example databases, some day ago it was failing with an not authorized error, and after the change from orientechnologies.com to orientdb.com we fail also to load the list of available databases.

this could be improved by handling http errors like redirect(301) and do by js the requsted action.

**Comment by marcolazzara** [comment]
If I undestand the question I want to give you my 2 cents. In order to avoide the http error (for example when you are behind a firewall) is it possible to download the database only via https ?

**Comment by lvca** [comment]
It's a problem of website after the switch to orientdb.com.

**Comment by tglman** [comment]
but yes, using https will help to skip all caches and other things in the middle, but anyway have the zips cached somewhere help to not overload the server, it could be implemented as a second try in case of error.

**Comment by lvca** [comment]
Is it working now?
