### ISSUE TITLE
OrientDB studio as a basis for apps.

### ISSUE THREAD

**Issue by Arne-Pfeilsticker** [orientechnologies/orientdb-studio#257]
I would like to use OrientDB studio as the basis for an open source app. Is there any detailed documentation that will help me with this?

**Comment by maggiolo00** [comment]
hi @Arne-Pfeilsticker here is some documentation on how to build studio. https://github.com/orientechnologies/orientdb-studio. Studio is a pure javascript (AngularJs) project you can customize it but there is no documentation about the code.

**Comment by Arne-Pfeilsticker** [comment]
Hi Enrico, thanks for the quick response. I have already installed OrientDB Studio in WebStorm and running. I also read everything I could find on the internet about the studio. Nevertheless, I'm still a little bit lost. 
What is the core of the application, I could isolate and can build my application on top? What is the intended use of the controller, services, etc.?
My impression is that you've done a fantastic job. And if you could turn it into a starter-kit for angular apps, that would help tremendously and would also be very beneficial for OrientDB.

If you could help me, I would love to contribute to such a OrientDB App kit.

**Comment by lvca** [comment]
Closing this issue. In case please continue this discussion on Community Group: https://groups.google.com/forum/#!forum/orient-database
