### ISSUE TITLE
Collision of (angular specific) property $$hashKey 

### ISSUE THREAD

**Issue by wotamann** [orientechnologies/orientdb-studio#262]
If you use in a cluster the angularspecific property  '$$hashKey' with duplicate values then Studio throws the AngularJS Error: [ngRepeat:dupes]

The example above can be resolved by using track by $index, which will cause the items to be keyed by their position in the array instead of their value:

See: https://docs.angularjs.org/error/ngRepeat/dupes?p0=result%20in%20$data&p1=object:object:5

**Comment by maggiolo00** [comment]
do you experience this in browse ui?

**Comment by wotamann** [comment]
Yes I experienced this in Browse-Studio using a class with a property   '$$hashKey' and records containing duplicate values, which seems to be misinterpreted by ng-repeat.

btw - Thanks for making Orientdb, it is really a great and fast DB.

**Comment by maggiolo00** [comment]
How do you create a property with $$hashKey name?

**Comment by maggiolo00** [comment]
with ODB 2.1.x with Strict sql you will get an error

**Comment by maggiolo00** [comment]
However fixed :D
