### ISSUE TITLE
Installation: grunt server command does not work

### ISSUE THREAD

**Issue by ropeladder** [orientechnologies/orientdb-studio#264]
I'm probably making some obvious rookie mistakes, but I'm trying to follow the installation instructions and failing:

1. grunt doesn't actually get installed so that it's usable on the command line for the final command

2. when I do install grunt (using "npm install -g grunt-cli") there is still no "server" file in the root directory for it to run, so it just gives me a file not found error

**Comment by ZDorian** [comment]
Hi Ropeladder,

Did you follow the quick start guide? 
https://github.com/orientechnologies/orientdb-studio#quick-start

Remember to run npm install command whit "sudo".

Regards
Z

**Comment by abrausch** [comment]
I got the following verbose output:
```
marvin:orientdb-studio(78700m|master) $ grunt -v server                                                                                               ():[15:14]
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>>     at Object.exports.inherits (util.js:634:43)
>>     at Object.<anonymous> (/xxx/Desktop/orientdb-studio/node_modules/grunt-connect-proxy/node_modules/http-proxy/lib/http-proxy/index.js:106:17)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/xxx/Desktop/orientdb-studio/node_modules/grunt-connect-proxy/node_modules/http-proxy/lib/http-proxy.js:4:17)
>>     at Module._compile (module.js:460:26)

Running tasks: server
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by maggiolo00** [comment]
It is a problem with proxy
see here https://github.com/drewzboto/grunt-connect-proxy/issues/97

I will update the package

**Comment by abrausch** [comment]
Great, I just manually updated the package and it works now. Thanks a lot

**Comment by ZDorian** [comment]
It works !
