### ISSUE TITLE
Support batch in Studio

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#267]
The user could switch between "command" (current and default) and "batch".

**Comment by obi1kenobi** [comment]
I've been trying to figure out how to use batch in Studio, but I haven't had any success. I wrote a query like the following into the query text box:
```
begin
let foo = select * from Foo limit 2
let bar = select * from Bar limit 3
commit
return (SELECT $foo as foo, $bar as bar)
```
but that just gave me an error message:
```
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.begin let foo = select * from Foo limit 2 let bar = select * from Bar limit 3 commit return (SELECT $foo as foo, $bar as bar)
    DB name="foobar"
```

I also wasn't able to find any documentation on what the correct way to do this is. Any suggestions? Also, would you prefer if I made a new issue for this, or is this okay?

**Comment by obi1kenobi** [comment]
It appears that I get the same error when attempting to run the command via `pyorient`, the Python OrientDB client.
