### ISSUE TITLE
Enhancement request to show the edge properties instead of edge class in the graph view

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb-studio#269]
I am using OrientDB Studio 2.1rc2. We would like to have an enhancement in studio graph editor. The graph editor in studio does not show the properties of the edges in the graph view. For vertices, it is possible to select the property to be displayed on the vertex. Similar to this, it should be possible to select the property to be displayed as edge label, instead of always showing the edge class name.

**Comment by 0xfff** [comment]
+1

**Comment by maggiolo00** [comment]
Implemented in 2.2.x. 

https://github.com/orientechnologies/orientdb-studio/commit/c2d94b097616a8d92b0e9e737eaf3be958c9ddcf
