### ISSUE TITLE
Schema Tab: Hide unnecessary columns

### ISSUE THREAD

**Issue by phamptu** [orientechnologies/orientdb-studio#273]
I think current default view of Schema tab have a lot of unuseful information that normal user don't want to see again and again after visit. 

You may consider to :
- Hide unnecessary columns in Schema tab (Alias, Abstract, Superclass, Cluster selection), all of this information only show if user click on "More information" button
- Seperate between system's class and user's class, by default, hide all system's class because a normal user / developer don't care much about system's class.

**Comment by kwoxer** [comment]
Jap good points. I totally agree.

But prio: low =)

**Comment by maggiolo00** [comment]
+1

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by santo-it** [comment]
Hi @phamptu ,

Thanks for opening this issue and for your feedback

About your second suggestion: starting from OrientDB v.2.2.15, classes are by default divided into two main groups: "User Classes" and "System Classes". User classes are groped by "Vertex Classes", "Edge Classes" and "Generic Classes"

Many thanks,

**Comment by lvca** [comment]
We improved schema panel.
