### ISSUE TITLE
Error text with wrong color and spelling mistake

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#276]
Pretty simple. I'm logged with a user with lowest rights. Now I tried to save a new vertex.

Then I somehow got back a green box on the bottom. That's a totally wrong colour that implicates that everything is fine... but actually it's a huge error. And somehwere else I also get back a red box. So I know it's possible ;)

http://i.imgur.com/UEMfp8d.png

And please instead of **no** say **not**. Or just leave away the *the*.

**Comment by maggiolo00** [comment]
Hi @kwoxer Which Version?

**Comment by maggiolo00** [comment]
2.0.x?

**Comment by kwoxer** [comment]
2.0.5, should I recheck with the latest?

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
