### ISSUE TITLE
Distinct function somehow not giving back all types

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#277]
An important issue I would love to see solved. Please let us discuss this issue on SO.

http://stackoverflow.com/questions/30380034/distinct-function-somehow-not-giving-back-all-types

**Comment by santo-it** [comment]
Hi,

Thanks for opening this. I think this can now be closed. You got some help in the SO thread as far as I see. I do not see actions related to Studio that have to be taken here

Studio applies a LIMIT - but you can also set -1 to get all records

I'm closing this issue. Please feel free to comment if more help is needed

Thanks,
