### ISSUE TITLE
Bug on vertex cleared from canvas and edge label of siblings vertexes

### ISSUE THREAD

**Issue by AlessioDeAngelis** [orientechnologies/orientdb-studio#286]
Hello,
we noted a bug on the edge visualization after removing a vertex from the canvas.
Let's consider we have a vertex, with four outgoing edges: in particular three belong to one class (edgeA) and the last one to another one (edgeB).
Now, if we want to delete from canvas one adjacent vertex with incoming edge A, it happens that the vertex is actually cleared from canvas but the edge with label edgeB linked to a sibling changes its own shown label to edgeA.
In the following picture I summarized the flow (before clearing #14:1, during clearing #:14:1 and after clearing #14:1).
![bug_canvas](https://cloud.githubusercontent.com/assets/1493765/7910065/98de7d16-0851-11e5-8971-57e776f3b6e3.png)

Thank you.
Cheers,
Alessio

EDIT:
Concerning this issue, I noted that the edge that is cleared from the canvas is the last one of the outgoing edges list and not the one that is actually linked to the vertex to be cleared.

**Comment by AlessioDeAngelis** [comment]
Concerning this issue, I noted that the edge that is cleared from the canvas is the last one of the list of outgoing edges and not the one that is actually linked to the vertex to be cleared.

**Comment by maggiolo00** [comment]
@AlessioDeAngelis 

does this happen with the latest 2.2.10?

**Comment by maggiolo00** [comment]
@AlessioDeAngelis 

I'm closing this. Please reopen if it happens with 2.2.10
Thanks
