### ISSUE TITLE
Invalid results when selecting incoming edges

### ISSUE THREAD

**Issue by lodrion** [orientechnologies/orientdb-studio#290]
When selecting incoming edges (either on the console or on the web-ui), we sometimes see a super set of valid edges. A simple snippet from the console is 

orientdb {db=defacto}> select in from (select expand(in_CountryElection_Country) from #16:74)                                

----+------+-------
#   |@CLASS|in     
----+------+-------
0   |null  |#16:207
1   |null  |#16:207
2   |null  |#16:207
3   |null  |#16:207
4   |null  |#16:207
5   |null  |#16:207
6   |null  |#16:74 
7   |null  |#16:74 
8   |null  |#16:74 
9   |null  |#16:74 
10  |null  |#16:74 
11  |null  |#16:74 
12  |null  |#16:74 
13  |null  |#16:74 
14  |null  |#16:74 
----+------+-------

15 item(s) found. Query executed in 0.035 sec(s).

where one would have expected only edges with in == #16:74

The edge in question is fairly simple
orientdb {db=defacto}> info class CountryElection_Country

Class................: CountryElection_Country
Super class..........: E
Default cluster......: countryelection_country (id=24)
Supported cluster ids: [24]
Cluster selection....: round-robin
PROPERTIES
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
 NAME                          | TYPE        | LINKED TYPE/CLASS             | MANDATORY | READONLY | NOT NULL |    MIN    |    MAX    | COLLATE  |
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+
 in                            | LINK        | Country                       | false     | false    | false    |           |           | default  |
 out                           | LINK        | CountryElection               | false     | false    | false    |           |           | default  |
-------------------------------+-------------+-------------------------------+-----------+----------+----------+-----------+-----------+----------+

**Comment by maggiolo00** [comment]
@lodrion  i think this is not a studio issues can you open it here?
https://github.com/orientechnologies/orientdb/issues
