### ISSUE TITLE
Bug 2.1-rc3: sorting by any of the metadata fields doesn't work and kills pagination links

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb-studio#291]
In Browse Mode if I try to sort by @rid, @class or @version (metadata fields) it doesn't do anything and makes pagination links at the bottom to stop working. If I try sorting by something else pagination links start working again

**Comment by zifnab87** [comment]
It also seems that when doing a select without a limit the two pages that appear have exactly the same metadata and only the other columns change

**Comment by maggiolo00** [comment]
@zifnab87 
can you try with 2.1-rc5?

**Comment by zifnab87** [comment]
I tried and I have the same issue there as well

**Comment by zifnab87** [comment]
@maggiolo00 Tried with 2.2-alpha with the same results..

**Comment by maggiolo00** [comment]
In OrientDB 2.2 

the table component has been replaced with 
http://lorenzofox3.github.io/smart-table-website/
Sorting has been removed
