### ISSUE TITLE
2.1-rc3 : Limit 20 is appearing all the times regardless of the limit in the actual query

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb-studio#295]
In browse mode, Limit: 20 is appearing all the times regardless of the limit in the actual query

![image](https://cloud.githubusercontent.com/assets/526062/7974488/1ba18f88-0a30-11e5-8e89-3b37258f7219.png)

**Comment by maggiolo00** [comment]
That because it display the limit configuration.
But if you set the limit in your queries instead of the settings. Studio cannot know the limit that you use in the queries.

**Comment by zifnab87** [comment]
So it is misleading and probably not very useful since it appears regardless of the real set limit? And why it is not possible to know the limit from the query? I understand that parsing the query would be overkill but then the indication probably shouldn't be there at all imo..

**Comment by maggiolo00** [comment]
Fixed here in 2.2.2

https://github.com/orientechnologies/orientdb/issues/5271
