### ISSUE TITLE
Support new "sessionId" in connection information

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#297]
I've added `sessionId` reporting the sessionId if any. This helps to debug the sessionId used by the clients/drivers.

**Comment by maggiolo00** [comment]
i see that this changes has been made on 2.2.x
Should i move this on 2.2.x?

**Comment by lvca** [comment]
ok for 2.2

**Comment by maggiolo00** [comment]
Available in Studio 2.2.x
