### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#299]
Even with  query that takes 62ms, Studio takes 1000-1500ms to render the result.

**Comment by Ndrou** [comment]
The worst is the rendering classes for me.

We have 245 classes, and to display the schema tab, the request takes 320ms, and rendering takes about 20s!

**Comment by maggiolo00** [comment]
hi @Ndrou i'm opening a new issue to paginate the Schema page

https://github.com/orientechnologies/orientdb-studio/issues/328

**Comment by Ndrou** [comment]
:+1:

**Comment by a-unite** [comment]
Dear @maggiolo00 
Will filtering work with pagination too? Does it trip down to the server for updating the list?

I'm always aware to not click on the Schema tab. We have few hundred classes and I have to admit - it is rare situation, when I could find enough patience to not kill the page and reopen studio in another window.

Metadata requests are quite slow in ODB, but in case of  Studio, I believe, you could optimise Angular listeners (or how do they call it) to make things faster.

**Comment by maggiolo00** [comment]
hi @a-unite 

yes filtering will work with pagination.

**Comment by a-unite** [comment]
Got it, thanks.

**Comment by maggiolo00** [comment]
Resolved in 2.2.x
