### ISSUE TITLE
Graph view crashes on edit edge

### ISSUE THREAD

**Issue by skibaa** [orientechnologies/orientdb-studio#302]
1. Open GratefulDeadsConcerts db
2. Open some vertices with edges between them (see an example screenshot)
3. Right click on any edge and select pencil (edit) icon

404 page is shown in the background and the property editing dialog has no data.

![edge-edit](https://cloud.githubusercontent.com/assets/194390/8542979/427a8100-24a2-11e5-8727-c312f4ef4664.png)

![edit-edge1](https://cloud.githubusercontent.com/assets/194390/8542982/45fee8ca-24a2-11e5-856a-d25ba28b9100.png)

**Comment by maggiolo00** [comment]
Fixed
