### ISSUE TITLE
Graph view stops showing properties after selecting an edge

### ISSUE THREAD

**Issue by skibaa** [orientechnologies/orientdb-studio#303]
Version 2.1-rc3
Steps to reproduce:

1. Open GratefulDeadConcerts DB
2. Enter this query in the graph view: traverse in('written_by') from #9:50
3. Right click any Vertex and select the eye icon - properties are shown correctly
4. Left click any Edge - properties disappear. Sometimes the properties of the vertex remain on the screen instead of the edge.
![vew-vertex](https://cloud.githubusercontent.com/assets/194390/8543356/0dc89732-24a5-11e5-8448-6f61d33a8e48.png)
![edge-view](https://cloud.githubusercontent.com/assets/194390/8543366/13ca4036-24a5-11e5-9199-a4f5bc9e3069.png)

**Comment by maggiolo00** [comment]
Hi @skibaa 

it has been fixed. The problem was with lightweight edges. Not it show correctly that there are no properties

<img width="710" alt="screen shot 2016-06-16 at 11 52 09" src="https://cloud.githubusercontent.com/assets/98812/16112719/f5c0a912-33b8-11e6-8b44-746188c8de34.png">

**Comment by skibaa** [comment]
Thanks a lot! Will wait for the release to update.
