### ISSUE TITLE
OrientDB 2.0.12 Query issue

### ISSUE THREAD

**Issue by brahimrafik** [orientechnologies/orientdb-studio#304]
I am trying to execute this query via HTTP REST : 
select sum(in().size()) as nb ,* from Client where @RID=14:0

but I am getting this result bellow
<img width="1141" alt="screen shot 2015-07-08 at 18 16 39" src="https://cloud.githubusercontent.com/assets/6002793/8575669/8a3f7530-259d-11e5-84ec-b15149cf05b1.png">

And when I run it from Studio/Console it works just fine

<img width="1273" alt="screen shot 2015-07-08 at 18 18 47" src="https://cloud.githubusercontent.com/assets/6002793/8575726/dde92d7a-259d-11e5-85ee-41830526f12b.png">

Any ideas?

@brahimrafik

**Comment by lvca** [comment]
maybe the encoding is not correct. I suggest you to trace what Studio executes and do the same request (using POST for example)
