### ISSUE TITLE
Login into Studio (with a unique user) just working offline

### ISSUE THREAD

**Issue by kwoxer** [orientechnologies/orientdb-studio#307]
Feel free to test it on your own: http://arda-maps.org:2480/

I created a user *arda* with password *arda* and the login works on localhost, but not online like on the link above. Why so?

Do I need to change anything more?

It worked on Version **2.0.5**, but yesterday I updated to **2.0.12** and for sure created the database again. Now uploaded I cannot login anymore with the arda user. Other users (root...) work...

Btw: error is ```Invalid username or password ``` and there is nothing logged in the Server shell.

**Comment by maggiolo00** [comment]
If you create a new database are you able to login?

**Comment by kwoxer** [comment]
Can you tell me the steps for this maybe? I mean it is just with the single user.

**Comment by maggiolo00** [comment]
create a database from studio using the server credential and then login with 
admin/admin

**Comment by kwoxer** [comment]
http://arda-maps.org:2480/studio/index.html#/database/test/browse but how does this help me?

**Comment by maggiolo00** [comment]
So don't know.
How did you create the databases?

**Comment by maggiolo00** [comment]
The arda one

**Comment by kwoxer** [comment]
With these few lines:

```java
db.command(new OCommandScript("sql", "insert into orole set name = 'ardaRole', mode = 0")).execute();
			db.command(new OCommandScript("sql", "update orole put rules = 'database.class', 2 where name = 'ardaRole'")).execute();
			db.command(new OCommandScript("sql", "update orole put rules = 'database.function', 2 where name = 'ardaRole'")).execute();
			db.command(new OCommandScript("sql", "update orole put rules = 'database.cluster', 2 where name = 'ardaRole'")).execute();
			db.command(new OCommandScript("sql", "insert into ouser set name = 'arda', password = 'arda', status = 'ACTIVE', roles = (select from ORole where name = 'ardaRole')"))
					.execute();
```

**Comment by maggiolo00** [comment]
do you have something strange on the server log?

**Comment by kwoxer** [comment]
No there is absolutely nothing =(

**Comment by kwoxer** [comment]
Very strange ... today I tried to login on localhost and now I get the same message ...

So there is something broken in the 2.0.12 version of OrientDB =( Even when I login with root and change the password of the user *arda* I still cannot login with it.

Ahh found it! The role is somehow wrong. When I set a usual role like admin or reader, everything works again and I can login again. 

Might you tell me @maggiolo00 what is missing for minimal rights I want to give to that user?

**Comment by kwoxer** [comment]
I will try some things tomorrow, but really strange that something of the right management has been changed.

**Comment by kwoxer** [comment]
Maybe I'm totally dumb or so, but I just reuploaded the database and now it works...

Seems that there was something wrong with the upload these days =/ Sorry.

**Comment by lvca** [comment]
In case you see this issue again, please reopen it ;-) Thanks.
