### ISSUE TITLE
grunt server does not run (master/head)

### ISSUE THREAD

**Issue by acmeguy** [orientechnologies/orientdb-studio#311]
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "server" not found. Used --force, continuing.

Done, but with warnings.
stefan@midnightoil:/var/www/as/orientdb-studio$ grunt server
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "server" not found. Use --force to continue.

**Comment by maggiolo00** [comment]
Did you try with develop branch?

**Comment by mael-morel** [comment]
Hi, same problem here. Solved by replacing the grunt-connect-proxy value in package.json : 
```
"grunt-connect-proxy": "git://github.com/ruiaraujo/grunt-connect-proxy#patch-1"
```

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
