### ISSUE TITLE
When adding a new permissions rule in studio the permissions must be restricted to the list of resources supported by OrientDB internally

### ISSUE THREAD

**Issue by nagarajasr** [orientechnologies/orientdb-studio#314]
Studio allows to edit the permission rules by setting any name for the permission: 

![image](https://cloud.githubusercontent.com/assets/7237012/9006249/d2ceaa70-37a2-11e5-9c09-c1fd3e1541c1.png)

here the permission name added 'asdasdad' is not of any relevance as it does not match any of the pre-defined list of resources of OrientDB. in fact the data is inserted in the orole as 'null' and fails to retrieve it when studio is refreshed.

**Comment by lvca** [comment]
You can define your own app-level resources.

**Comment by lvca** [comment]
This is the reason why it's an open field.
