### ISSUE TITLE
'Authenticated Required' popup shows multiple times and doesn't log me in

### ISSUE THREAD

**Issue by oren** [orientechnologies/orientdb-studio#320]
I use the official docker container - https://github.com/orientechnologies/orientdb-docker
and run it on my laptop (localhost:2480).

I am first greeted with the authentication form and I am able to authenticate using 'root', 'root'. than i try to import a public database and click on one of the databases. now I see the authentication popup again and even after entering 'root', 'root', it doesn't let me 'login'.

**Comment by SDIPro** [comment]
Can no longer reproduce.
