### ISSUE TITLE
cannot log in to workbench after password change

### ISSUE THREAD

**Issue by tellyarz** [orientechnologies/orientdb-studio#321]
I have OrientDb enterprise workbench 2.1.0 installed. Last week I changed the default password and could log in after then but today, I cannot log in with the new password I created. How can I edit the log in details or how can I correct this issue?

**Comment by maggiolo00** [comment]
Which password did you change?

**Comment by tellyarz** [comment]
password for logging into the workbench website console

**Comment by maggiolo00** [comment]
With Change Password?

**Comment by tellyarz** [comment]
sorry I did not understand your last comment. Normally, when I newly installed and stared workbench, I used username and password of admin to gain access to the website for workbench. I later changed the password, refreshed and logout, then tried that same day with the new password, everything went well. Today its not accepting the password

**Comment by maggiolo00** [comment]
do you see something in the log?

**Comment by tellyarz** [comment]
okay, for that, I found out that the Log is stuck with just this same line: "WORKBENCH looking for hazelcast cluster...

**Comment by maggiolo00** [comment]
That is not a problem. It is normal logging.
Seems strange i think is not a password problem if you were able to log after 
the change. can you zip the database monitor under the database directory in the WB distribution?
andsend it me?

**Comment by tellyarz** [comment]
okay, which email will I send it to?

**Comment by maggiolo00** [comment]
you can send it to e.risa@orientdb.com
Thanks

**Comment by maggiolo00** [comment]
@tellyarz 
i was able to login with the default  'admin' & 'admin'

**Comment by tellyarz** [comment]
Really, Just did that now too. What would have gone wrong?

**Comment by maggiolo00** [comment]
Don't know i thought that you changed the password.
However you can simply stop the WB delete the database and restart it if something goes wrong

**Comment by tellyarz** [comment]
Okay. Thanks.
