### ISSUE TITLE
OrientDB Studio creates unnamed cookie with zero length

### ISSUE THREAD

**Issue by wcraigtrader** [orientechnologies/orientdb-studio#323]
With OrientDB Community 2.0.10, running embedded in our application, the Studio Web Interface runs generally as expected, but recently we ran a security scan on it (as part of our application release process) and discovered that under certain circumstances, a browser cookie is created that is bound to path /studio/ but which no name, and no value. I have been able to replicate this with FireFox 39.0 on Mac OSX.

Our security team wants to know how this cookie is used, and if it is actually necessary.

**Comment by wcraigtrader** [comment]
![orient-studio-no-name-cookie](https://cloud.githubusercontent.com/assets/972263/9534003/a5f97600-4ce3-11e5-9ebd-6ffc33de49e4.png)

Screen shot of Firefox, showing no-name cookie with no value.

**Comment by maggiolo00** [comment]
hi @wcraigtrader 
i'm inspecting this. Seems strange a cookie without name. 
I Will let you know

**Comment by prjhub** [comment]
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.
