### ISSUE TITLE
Orient Studio uses Basic Authentication

### ISSUE THREAD

**Issue by wcraigtrader** [orientechnologies/orientdb-studio#324]
The Orient Studio administration application uses form-based authentication on its home page (in order to correctly select a database), but uses HTTP basic authentication on all other requests. Our infosec group refuses to allow us to use this application because it only obscures the user/password instead of using a hash-based method such as Digest authentication.

**Comment by wcraigtrader** [comment]
We've currently configured the Studio interface as follows:

    <listener protocol="http" socket="default" port-range="2480-2490" ip-address="0.0.0.0">
      <commands>
        <command implementation="com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetStaticContent" pattern="GET|www GET|studio/ GET| GET|*.htm GET|*.html GET|*.xml GET|*.jpeg GET|*.jpg GET|*.png GET|*.gif GET|*.js GET|*.css GET|*.swf GET|*.ico GET|*.txt GET|*.otf GET|*.pjs GET|*.svg GET|*.json GET|*.woff GET|*.ttf" stateful="false">
          <parameters>
            <entry value="Cache-Control: no-cache, no-store, max-age=0, must-revalidate\r\nPragma: no-cache" name="http.cache:*.htm *.html"/>
            <entry value="Cache-Control: max-age=120" name="http.cache:default"/>
          </parameters>
        </command>
        <command implementation="com.orientechnologies.orient.graph.server.command.OServerCommandGetGephi" pattern="GET|gephi/*" stateful="false"/>
      </commands>
      <parameters>
        <parameter value="utf-8" name="network.http.charset"/>
      </parameters>
    </listener>

**Comment by kwoxer** [comment]
Sorry but how was your question? Or what is the issue?

**Comment by wcraigtrader** [comment]
The issue is that using Basic Authentication for web application authentication has been considered a bad practice for more than a decade. Our internal infosec group won't let us deploy our application with the Orient Studio active as long as it uses Basic Authentication. My question was whether or not Orient was going to use something more secure (such as browser cookies) to authenticate access to Studio.

**Comment by kwoxer** [comment]
http://stackoverflow.com/questions/30601601/first-time-orientdb-user-regarding-security-in-rest-api
http://stackoverflow.com/questions/30117149/how-to-authenticate-a-http-request-to-an-orientdb-function-on-angularjs

Did you already check these? But afaik you can use orientjs for hiding the credentials. Isn't that correct?

**Comment by wcraigtrader** [comment]
@kwoxer Again, my problem is that I need to disable Basic Auth for the Studio web app, and enable some other form of authentication because my InfoSec team won't allow a web app that uses Basic Auth. I don't need OrientJS and I don't need or want the Orient REST API -- my application's in Java and is using the normal Java APIs. I just wanted to be able to deploy the Studio app for remote management.

**Comment by lvca** [comment]
Hey guys, OrientDB v2.2 is very focused about security, we already did a lot (SALTed passwords, encryption at rest (DES/AES on storage), disabled of access to OUSer, mask of passwords on Server's console and salted password also in the server).

So if you have any idea about this, please make a proposal and I'll do my best to put it in next release.

**Comment by digitalacorn** [comment]
It seems the password entered on installation is stored in the config/orientdb-server-config.xml file. And is stored in plain-text. I haven't explored to see if there are other configuration options to change the storage method  - but I would expect the default to be more secure 'out of the box'. I'm also having basic-auth issues in that I't won't seem to accept any credentials at all.

**Comment by lvca** [comment]
I'm back on this. In v2.2 passwords are not in clear, but rather hashed with SALT. About an alternative method to login from Studio, this is interesting and it will be supported in the future for sure.
