### ISSUE TITLE
Edit Vertex: refresh issue after creating an edge

### ISSUE THREAD

**Issue by mindplay-dk** [orientechnologies/orientdb-studio#325]
Given a trivial example like e.g. `Employee extends V` and `WorksAt extends E`, creating a `WorksAt` edge via the left/right-hand "in" and "out" panels when editing an `Employee`, doesn't seem to work?

When I press the `+` button, select the `WorksAt` class, and press "save", the added edge simply disappears and doesn't get saved.

**Comment by santo-it** [comment]
Hi @mindplay-dk,

Many thanks for opening this issue. There are indeed a few problems creating edges this way. However, I was able to workaround them

Note also that you can create edges via the graph editor as well

Let me write the steps I used to create an edge while editing a vertex: let's suppose we want to create an OutEdge:

- click on the + button close to the "Out Edges" text, and select the WorksAt class
- click on the plus button close to the "WorksAt" list-item just created - a new "Create Edge" window will appear
- write a query in the new window to find a vertex, click on "run" to execute the query, and select the vertex you want to link. Click on the "create edge" button on this window
- the window will disappear and the edge is created

Note: there's a refresh issue right now and as a result the edge is not displayed under the WorksAt" list (if you refresh from the browser you will see it)

Hope this helps
