### ISSUE TITLE
The list of functions are not displaying

### ISSUE THREAD

**Issue by GiulianoFranchetto** [orientechnologies/orientdb-studio#327]
Hi,

when I go to the function tab on orientdb studio, the functions I created are not displayed on the left black panel. That's kid of annoying because to update a function, I need to update the entry directly in the Ofunction database.

Is this a bug, or a misconfiguration from me?

Bye

**Comment by maggiolo00** [comment]
hi @GiulianoFranchetto 

which version of OrientDB?

How can i replicate this issue?

**Comment by GiulianoFranchetto** [comment]
hi @maggiolo00 

the version is 2.1.2 community. I first created 1 function, and everything was fine. Then I created another one by clicking on the New button. 

The issue is that my first function is not in the left black panel. I cannot edit it anymore (without updating directly the OFunction database)

I don't think I did nothing more interesting than this

**Comment by maggiolo00** [comment]
@GiulianoFranchetto  
i tried with 2.1.4 but i'm not able to reproduce it
https://www.dropbox.com/s/zhme7wghf3kjzi3/screencast.mov?dl=0

**Comment by GiulianoFranchetto** [comment]
Well that's strange. 
I'll try to upgrade. The server runs on a small dev virtual machine. Maybe the lack of memory can be the issue

**Comment by maggiolo00** [comment]
which browser do you have?
i tried with Chrome

**Comment by GiulianoFranchetto** [comment]
Chrome too

**Comment by maggiolo00** [comment]
Strange. Can you try with 2.1.4. But i think nothing changed in Functions Management

**Comment by GiulianoFranchetto** [comment]
I'll try on my own computer at home. It may be a strange issue with the browser. I think you can close the issue, it seems it has nothing to do with studio itself.

thanks for the help !

**Comment by maggiolo00** [comment]
@GiulianoFranchetto  maybe it is a resolution problem
Which resolution do you have?

**Comment by GiulianoFranchetto** [comment]
1920*1080

**Comment by maggiolo00** [comment]
Do you have the chrome inspector opened? I noticed that functions disappear when i have it opened

**Comment by GiulianoFranchetto** [comment]
Thanks, that was it!
I might have it opened when I opened studio.

**Comment by maggiolo00** [comment]
Cool. BTW i will try to solve it.

**Comment by maggiolo00** [comment]
Fixed
