### ISSUE TITLE
How to remove edge from connected broken vertex in orientdb

### ISSUE THREAD

**Issue by harshalkadam16** [orientechnologies/orientdb-studio#329]
I have user vertex and portfolio vertex that connected to USER_PORTFOLIO_EDGE. but portfolio vertex was delete still there is edge on user vertex that shows deleted vertex rid. so how can i delete that edge. Thanks in Advance

**Comment by luigidellaquila** [comment]
Hi @harshalkadam16 

This can happen if you work in noTx mode, we always suggest to use transactional connections when working with graphs. 
You can remove hanging references using document API, eg.

```sql
update <user_rid> remote out_USER_PORTFOLIO_EDGE = <edge_id> 
delete from <edge_id> 
```

**Comment by luigidellaquila** [comment]
sorry, you have to add UNSAFE at the end of these statements, otherwise the graph layer will complain.

**Comment by luigidellaquila** [comment]
Just last question, how did you delete the vertex? Did you use DELETE VERTEX statement?
If you use a simple DELETE FROM ... UNSAFE then it's normal to have hanging edges.

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @harshalkadam16 

did this solve your issue? Can I close this

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @harshalkadam16 

I'm closing this, please reopen if you need further info

Thanks

Luigi
