### ISSUE TITLE
Read group users unable to login to Studio

### ISSUE THREAD

**Issue by SatishAMP** [orientechnologies/orientdb-studio#330]
2.0.13 , Users created with Read group access are unable to login to studio , is this bug or expected functionality ?

**Comment by luigidellaquila** [comment]
Hi @SatishAMP,

There is no known limitation or issue about this, could you please share the content of "Read" group record?

Thanks

Luigi

**Comment by SatishAMP** [comment]
Hi Luiji, I have shared the requested information in mails , Can you please let us know any update on this issue ?

**Comment by maggiolo00** [comment]
hi @SatishAMP 

can you try to connect using the console with that user?

**Comment by maggiolo00** [comment]
@SatishAMP 

did you manage to solve this issue?

**Comment by SatishAMP** [comment]
HI , No , not yet resolved , I will try with console and provide you the results

**Comment by maggiolo00** [comment]
hi @SatishAMP 

have you tried with console?

**Comment by SatishAMP** [comment]
Yes tried with Console , Able to login. Here are the steps followed. 
1. Login to Studio with admin and created new user with reader group.
2. Login in to console with below command : 
connect remote:x.x.x.x:2524/OrientDB aodsread aodsread
able to login and executed sql statments.
3.Logout from Studio and login as aodsread , able to login but within 1 mininute , it again prompting me for username & password from that time its not allowing to studio.

We have our support team inability to monitor the database  with this issue , So can you please look in to this with priority?

**Comment by maggiolo00** [comment]
hi @SatishAMP 

so after you create the user aodsread are you able to login with that user?

I just retried with OrientDB 2.0.13 and all works fine.

Can you send me the screenshot of your reader configuration in Studio?

**Comment by maggiolo00** [comment]
You can send it at e.risa@orientdb.com

**Comment by maggiolo00** [comment]
hi @SatishAMP 

once you login with reader, when the browser ask for credential can you please press `esc` and tell me which error gives studio?

**Comment by atofteland** [comment]
The studio gives me a "401 unauthorized." at the bottom of the screen

**Comment by maggiolo00** [comment]
hi @atofteland 
even with a user having admin roles do you get 401?
Where?
when you login or after?

**Comment by atofteland** [comment]
I created an id based on the admin id called andy.  I brought up the studio, I was originally logged in with admin.  I log out.  I then log in with andy.  It allows me in, then after a second it pops up a log in box.  The header of the box says Authentication Required.  Below that header it says "The server http://159.202.94.77:2481 requires a username and password.  The server says: OrientDB Server."  When I try to enter andy and its password nothing happens it asks for the user id/password again.  If I hit escape then I get the 401

**Comment by maggiolo00** [comment]
andy user has admin role right?

**Comment by atofteland** [comment]
Correct   taken from studio when logged in as admin:  
andy	
admin ×
Add role
ACTIVE

**Comment by maggiolo00** [comment]
ok i'm checking it.

which version of OrientDB do you have?

**Comment by atofteland** [comment]
Studio version : 2.0

OrientDB version : 2.0.18

Home Page : https://github.com/orientechnologies/orientdb-studio

Copyrights : Orient Technologies LTD

License : Apache 2

**Comment by atofteland** [comment]
I create the user using the following statement:  INSERT INTO ouser SET name = 'andy', password = 'mahesh', status = 'ACTIVE', roles = (SELECT FROM ORole WHERE name = 'admin').  Is this correct?  Also, is there a document that describes all of the steps to creating a new user?  I have looked in the manual, but am not sure if everything is done.  I'm not sure if I should have also put something into the xml configuration file too?

**Comment by atofteland** [comment]
I think I hit the escalate button, this is an important issue for us to get the users setup correctly so users do have the correct access.
