### ISSUE TITLE
Load balanced connection pools

### ISSUE THREAD

**Issue by thejjmiller** [orientechnologies/orientdb-studio#331]
I have a 3 node distributed OrientDb cluster. How would you setup my Connection in the .NET driver to load balance/fail over?

**Comment by lvca** [comment]
You cannot. This isn't supported by .NET driver. You should use the HTTP/JSON protocol and do a round-robin for calls between all the available servers. In Java driver this is automatic, but .NET will support this feature at Q1 2016, sorry.
