### ISSUE TITLE
saving the schema reports false changes

### ISSUE THREAD

**Issue by arisAlexis** [orientechnologies/orientdb-studio#334]
when changing a property's type etc the underlying mechanism works OK but what is reported in the save alert is the wrong property (and always the same in my case). 
using studio 2.1

**Comment by maggiolo00** [comment]
hi @arisAlexis 

how can i replicate this?

**Comment by arisAlexis** [comment]
Open studio 2.1, and in the schema tab open a class with two properties. First make the first one not_null and save, then the other one, then the first one. The name of the variable being changed is messed up if you do this.

**Comment by maggiolo00** [comment]
hi @arisAlexis 

Tested with Studio 2.2 seems to be fixed can you confirm?

**Comment by arisAlexis** [comment]
yes
