### ISSUE TITLE
Edge creation progressively slows down during ETL (OrientDB 2.1.4)

### ISSUE THREAD

**Issue by balemayehu** [orientechnologies/orientdb-studio#335]
When using ETL process to import additional 4.9 million Edges on a single server graph database, the import process starts off around 400-600 vertices/sec, but then progressively gets slower and grinds to almost a halt when it gets to about a million edges inserted.  JVM starts using up almost all of the physical memory available.  I have tried changing the MAXHEAP and MAXDISKCACHE settings based on recommendation in log file (MAXHEAP=-Xmx387m, MAXDISKCACHE="-Dstorage.diskCache.bufferSize=1519"), but that didn't provide any significant difference. I have also tried changing the ETL query below to use rid instead of the sub selects, but that didn't help either.

Current Graph Info:
100k User Vertex
100k AssetType2 Vertex
5mil AssetType1 Vertex
2.5mil Friend Edges (between user vertices)
100k BelongTo Edges (between asset type 2 and user)
100k ActedOn Edges (between asset type 1 and asset type 2)
100k Created Edges (between user and asset type 1)

Machine info:
Linux x86_64
4GB Mem
30GB disk with 75% free space
2 core CPU 2.4GHZ 

ETL json file:
{
  "source": { "file": { "path": "edge.csv" } },
  "extractor": { "csv": {"separator":"  " }},
  "transformers" : [
        {"command":{"command":"create edge Created from (select from User where id = ${input.source_id}) to (select from AssetType1 where id = ${input.dest_id})",
         "output": "edge"
        }}
  ],
  "loader" : {
    "orientdb": {
      "dbURL": "remote:localhost/mygraphdb",
      "dbAutoCreate": false,
      "dbUser": "admin",
      "dbPassword": "*",
      "dbType": "graph",
      "batchCommit": 1000
    }
  }
}

Is this a configuration issue, a resource constraint issue, or a limitation with Edge creation? Why does the JVM start to eat up all the memory? Your feedback is greatly appreciated. Thanks.

**Comment by balemayehu** [comment]
Moved issue to orientdb issues log

**Comment by kwoxer** [comment]
Did you also try it with a more difficult way like a complete Java import like this one http://www.kwoxer.de/2014/11/12/daten-import-via-java-orientdb-real-beispiel-tutorial/ ?
