### ISSUE TITLE
[Proposal] Handle errors more gracefully

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb-studio#340]
Hi there. I'm using the latest version of OrientDB at the moment (2.1.8). Maybe I'm the only one who complains about this problem, but anyway. I think it's quite annoying that Orient studio can't interpret the exceptions which it gets from the OrientDB server. I mean, when you, for example, create a class named `Cluster` (which I think should have been prohibited because it's a keyword that OrientDB uses) and then query this class like so:

```
select from Cluster
```

you'll get something like this:

![selection_001](https://cloud.githubusercontent.com/assets/3434800/12051561/67ab198e-af27-11e5-8f50-26242542a26d.png)

which is not very helpful at all.

Compare it to PgAdmin (PostgreSQL administration tool):

![selection_002](https://cloud.githubusercontent.com/assets/3434800/12051702/ab1ab49e-af28-11e5-8da1-8f6adf602502.png)

What I'm trying to say is that most of the errors that sometimes pop up from the Orient Studio don't give much clue what actually happened.

**Comment by maggiolo00** [comment]
hi @maseev 
studio just show you the error from query parsing as PgAdmin does.
As you can see 
the error is at line 1, column 8

What do you suggest studio should do to help you?

**Comment by maseev** [comment]
There's too much unrelated information. Instead of showing this:

```
com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Error parsing query: select from Cluster Encountered " <FROM> "from "" at line 1, column 8. Was expecting one of: <NULL> ... "true" ... "false" ... "{" ... <NULL> ... "{" ... "true" ... "false" ...
```

you can show something like that:

```
Error parsing query: select from Cluster Encountered " <FROM> "from "" at line 1, column 8.
```

It would be especially great if you could extract some extra information about the exception. For example, if a keyword was used in the place where it shouldn't you could show a related error information, so the client would know what to do. OrientDB could throw a special exception if a keyword was mistakenly used.

**Comment by luigidellaquila** [comment]
Hi @maseev 

the exception you see is generated by JavaCC (our SQL parser is based on that), it's a bit hard to dig into that and make it clearer.

In particular, it's hard for a parser to understand the intentions of who wrote the query, in this case maybe you are trying to query on a class whose name is `Cluster`, or you just forgot a part of the query, eg. `select from cluster:person`

Thanks

Luigi

**Comment by maseev** [comment]
@maggiolo00 Orient studio doesn't have the counters for line and column cursor position. So, users are supposed to count the lines and columns in their heads. Instead of this, OrientDB could point to the problematic piece of a query, As a result, your current, as well as, potential users, would be much happier.

**Comment by maggiolo00** [comment]
@maseev 

yes studio can point to the line/column with error by parsing the error from Server (Query Parser).

**Comment by maseev** [comment]
I don't think so. Maybe I'm supposed to click somewhere in order to trigger that behaviour? When I run a query that contains an error, the Orient studio simply displays an exception in the window and that's pretty much all.

**Comment by maggiolo00** [comment]
yes i mean Studio could do that.

**Comment by maseev** [comment]
Oh, I see. It would be great to have this feature in the Orient studio.

**Comment by maseev** [comment]
I think the current implementation is pretty good. Closing for now.
