### ISSUE TITLE
problem logging in with "reader" user

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/orientdb-studio#342]
Studio tries to read the "user" cluster after the authentication.
"reader" user has no read permission on that cluster, so it fails.
Studio should catch and manage the exception.

**Comment by fabriziofortino** [comment]
+1

Even if a user has READER/WRITER roles the Graph Editor is not accessible. Same problem for the Functions tab.

**Comment by santo-it** [comment]
Linked with https://github.com/orientechnologies/orientdb/issues/6479
