### ISSUE TITLE
studio index.html not found

### ISSUE THREAD

**Issue by bazo** [orientechnologies/orientdb-studio#344]
fresh 2.1.9 installed
when i go to domain:2480 it redirects me to domain:2480/studio/index.html but this gives error 404
NetworkError: 404 File not found - domain:2480/studio/index.html

what am i missing?

**Comment by lvca** [comment]
@bazo did you figure out the problem by your own?

**Comment by bazo** [comment]
yes, i am running orientdb process via supervisor and the first setup
screen has opened which i had not seen because it was hidden in logs
after i set the passwords and restarted everything was ok

would be nice if the web interface showed some warning though, and not a
blank page

**Comment by lvca** [comment]
Got it.
