### ISSUE TITLE
Table results view removes string `out_` from every property name

### ISSUE THREAD

**Issue by roko-p** [orientechnologies/orientdb-studio#346]
If you add a property named e.g. `pop_out_count` to an edge, the table view in the *Browse* tab will display that property as `pop_count`.

Here's an example:

![image](https://cloud.githubusercontent.com/assets/2991990/12351599/fd40019a-bb7e-11e5-8944-c05e23bf4d60.png)

**Comment by maggiolo00** [comment]
hi @roko-p 

which version?

It was fixed a while ago

https://github.com/orientechnologies/orientdb-studio/issues/322

**Comment by roko-p** [comment]
hi @maggiolo00 
This is in 2.1.6
Thanks

**Comment by maggiolo00** [comment]
hi @roko-p 

should be fixed in ODB >= 2.1.7

**Comment by maggiolo00** [comment]
hi @roko-p 
i'm closing this. It is fixed in OrientDB >= 2.1.7

Thanks
