### ISSUE TITLE
Studio show menu and actions for unauthenticated user!

### ISSUE THREAD

**Issue by christtrc** [orientechnologies/orientdb-studio#348]
When I login Studio with user 'reader', 'writer' or others and I have no permission to do something, but the menu items, action buttons showing to me.

I think all the controls without permissions should be hidden for unauthenticated user.

**Comment by santo-it** [comment]
Hi @christtrc ,

Thanks for opening this issue and for your patience. Totally agree on importance of having a smooth experience when using Studio with low-privileged users.

We have this in mind and in or list of critical things to do.

See also https://github.com/orientechnologies/orientdb-studio/issues/342  

Many Thanks,

**Comment by lvca** [comment]
Not relevant, closing it. (no community interest on it)
