### ISSUE TITLE
regarding login page

### ISSUE THREAD

**Issue by utkarshupreti** [orientechnologies/orientdb-studio#350]
I have deployed orientdb in is third party cloud server and login page is available to everyone via which number of database instance can easily be figure out.

Is there a way to either change default login page name or via any means it can be hide.

**Comment by maggiolo00** [comment]
hi @utkarshupreti 

you cannot change the login page or hide it. 

But you could protect the api /listDatabases so you have to know the root password in order to know the available databases.
in the orientdb-server-config.xml
remove the line with user `guest` and restart OrientDB.
