### ISSUE TITLE
Graph seems to be broken

### ISSUE THREAD

**Issue by sebastiandev** [orientechnologies/orientdb-studio#351]
Using both orientd-2.1.9 and orient-2.2.0 when I do a simple query
```sql
SELECT FROM V
```
![image](https://cloud.githubusercontent.com/assets/1094887/13018809/a5677ccc-d1aa-11e5-8ebe-4ad83361c912.png)

I get a set of vertices, but sometimes there are some edges missing.. so if I go and run another query (without clearing the canvas)

```sql
SELECT FROM E
```
![image](https://cloud.githubusercontent.com/assets/1094887/13018828/b52f8bae-d1aa-11e5-83e6-876f60b42ee6.png)

There you can see that 11:20 appeared linking both 11:15 and 11:7. But still I get 11:3 floating around with no edges, but when I go to Browse section and select that particular vertex, I found that it actually had an outgoing edge.
![image](https://cloud.githubusercontent.com/assets/1094887/13018909/23583478-d1ab-11e5-922f-18eb76a584f7.png)

And the edge has both IN and OUT vertices
![image](https://cloud.githubusercontent.com/assets/1094887/13019052/cf2c5554-d1ab-11e5-8464-8982047d2437.png)
Looks like 11:3 should be linked to 11:20 as well...

> If you do it the other way around, query for edges, then for vertices, you will see that new vertices show up floating around with no edges.

I' wondering if it has something to do with the limit of 20 vertices that you get by default, i have 22 vertices and 22 edges. I changed that on the Browse section but I'm not sure how that is handled on the graph view.

**Comment by maggiolo00** [comment]
hi @sebastiandev 
from the Graph View you can do

```
SELECT FROM V LIMIT -1
```

**Comment by maggiolo00** [comment]
@sebastiandev 

did you try to use limit -1?

**Comment by sebastiandev** [comment]
I think is working  now. thanks!
