### ISSUE TITLE
Orientdb 2.2 Alpha - Cannot create vertex on a specified cluster when key word CLUSTER is in all caps

### ISSUE THREAD

**Issue by cvm1ll3** [orientechnologies/orientdb-studio#352]
This only happens when strictSql is on:

example:
<code>CREATE VERTEX Person CLUSTER Person_USA set name =  "John"</code>

it gives the following error:
<code>com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Encountered " <IDENTIFIER> "CLUSTER "" at line 1, column 24. Was expecting one of: <EOF> <RETURN> ... ";" ... "cluster" ... "cluster" ... <RETURN> ...</code>

when I switch it to:
<code>CREATE VERTEX Person cluster Person_USA set name =  "John"</code>

then it will work OR when I turn off strictSql. 

I'm not sure if this is a big deal or if its even an error since the strictSQL parsing is ON, but I was using the same code in 2.1.11 and this wasn't an issue even if strictSQL is ON.

**Comment by maggiolo00** [comment]
hi @camilleenero 

can you retry with orientdb-2.2.0-beta?

**Comment by camilleenero** [comment]
hi @maggiolo00 just tried it in orientdb-2.2.0-beta and cluster works (uppercase or lowercase). I did notice something weird in the Studio, initially classes E,V and _studio have 8 clusters, and whenever I create a new class, it creates 8 clusters for that class (8 including the default cluster). Is that normal?

**Comment by maggiolo00** [comment]
hi @camilleenero 

yes it is normal

http://orientdb.com/docs/2.1/Tutorial-Clusters.html#understanding-clusters

**Comment by camilleenero** [comment]
hi @maggiolo00 

Is there a way to remove the initial multiple clusters in orientdb 2.2 beta? (besides manually or programatically removing it?). On our current schema, I use clusters heavily. Almost all of my classes have clusters, and I know the limit is 32K+, but if possible I don't want unnecessary clusters in the database. Is there a downside removing the clusters that were created by default if I rely on my own clusters anyway?

Thank you so much for your time.

**Comment by cvm1ll3** [comment]
Hi @maggiolo00 

For orientdb 2.2Beta, how do I set the minimumclusters to 1 before I create the database so classes E, V and _studio will only have 1 cluster initially after the creation of the database? Is it in the config xml file? I'd rather set it before the database gets created, rather than alter the database and manually delete the other clusters for classes E, V and _studio.

Thanks!

**Comment by maggiolo00** [comment]
hi @cvm1ll3 

You can set a global configuration like described here

https://github.com/orientechnologies/orientdb-docs/blob/master/Configuration.md#classes
