### ISSUE TITLE
Needs clarification regarding db connection in multi tenant application

### ISSUE THREAD

**Issue by JOSHI919** [orientechnologies/orientdb-studio#358]
I am using orientDB in multi tenant application, my use case is as per tenantID db connection will be opened if not already exist.
I am also sharing same connection among different operations.

For each tenant there is seprate database folder.

Requesting you to please analyse below code and let me know if any changes are required.

Once all opertaions are completed i am closing ODatabaseDocumentTx object (in finall block) but not closing OPartitionedDatabasePoolFactory object.

Is it required every time to close OPartitionedDatabasePoolFactory object also ?

Please also explain me how OPartitionedDatabasePoolFactory works on each request to figure out if connection for specific tenant exist or not.

	public  ODatabaseDocumentTx  getDocumentDBConnection(String tenantID)   throws Exception{
		OPartitionedDatabasePoolFactory poolFactory = null;
		OPartitionedDatabasePool pool = null;
		
		try{
			poolFactory = new OPartitionedDatabasePoolFactory(1);
			pool = poolFactory.get(DBURL+tenantID,"username", "password");
			return pool.acquire();
				
		}

	public void mainOperation(String tenantID){

		try{
		ODatabaseDocumentTx dbConn = getDocumentDBConnection(tenantID);

		 secondOperation(dbConn){}
		 thirdOperation( dbConn) {}
			
			
			like so on till 10 opertaion

		tenthOperation(dbConn){} 
		dbConn.commit;
		}
			catch(Exception   e ){
			dbConn.rollback(); 
			}
		finally{
			dbConn.close();
			}

		}

		public void secondOperation(ODatabaseDocumentTx dbConn) throws Exception{
				
			dbConn.activateOnCurrentThread();
			db connection used for hitting  orient database

		}

		public void thirdOperation(ODatabaseDocumentTx dbConn) throws Exception{
				
			dbConn.activateOnCurrentThread();
			db connection used for hitting  orient database

			}
					
		public void tenthOperation(ODatabaseDocumentTx dbConn) throws Exception{
				
			dbConn.activateOnCurrentThread();
			db connection used for hitting  orient database

			}

**Comment by tglman** [comment]
hi @JOSHI919,

You should keep just one instance of the factory, and reuse it far all the cases, the database should be closed after each block of operation.

the `dbConn.activateOnCurrentThread();` should not be needed, each thread should get the database from the factory and close it,  you should not share database istances betwheen threads.
