### ISSUE TITLE
OrientStudio makes sure you are notified when you do something wrong in the query

### ISSUE THREAD

**Issue by warriorkitty** [orientechnologies/orientdb-studio#360]
[Image](http://s22.postimg.org/c657z8vzk/Screen_Shot_2016_03_12_at_14_32_07.jpg)

Well, it's not an issue but I have to admit I'm scared now every time I need to press the Run button. :dancer:

**Comment by maggiolo00** [comment]
@warriorkitty 
Fixed in 2.2.x
