### ISSUE TITLE
Can not close error message.

### ISSUE THREAD

**Issue by elfet** [orientechnologies/orientdb-studio#361]
If message too big.
And please, add autocomplete to studio.
![localhost 2480 studio index html database eightd browse](https://cloud.githubusercontent.com/assets/141232/13724249/b7ad0f2c-e8b2-11e5-863a-8a2df744dc1a.png)

**Comment by maggiolo00** [comment]
hi @elfet 

i'm closing this. It is duplicate see here
https://github.com/orientechnologies/orientdb-studio/issues/360
