### ISSUE TITLE
Graph Editor and Schema Manager : Saving configuration doesn't persist 

### ISSUE THREAD

**Issue by Pamac** [orientechnologies/orientdb-studio#363]
I found this issue closed but i use v2.1.13 and it's not possible to persist Graph configuration and schema color... Thanks for your help.

**Comment by Pamac** [comment]
Using firebug i found that each time i click on "Save colors config" button, 2 POST are made 

   - the first one 
http://127.0.0.1:2480/command/databasetest/sql/-/-1?format=rid,type,version,class,graph

  - the second one
http://127.0.0.1:2480/document/databasetest/-1:-1 and the json containing good colors but a @rid  is strangely equals to #-1:-1

if i request with "select from _studio" a new record of GraphConfig is present with a @rid #25:12

but this graph config is never reloaded. Hope it can help you.

**Comment by maggiolo00** [comment]
@Pamac 

did you use root user?
can you try with user `admin`?

**Comment by Pamac** [comment]
`admin` does the job ! Thanks
