### ISSUE TITLE
Node editor shows bookmarks in graph mode

### ISSUE THREAD

**Issue by sowmyav82** [orientechnologies/orientdb-studio#364]
I have a simple graph as of now (less than 10 nodes). Viewing it from Graph sub-menu, when I select edit a node, it shows "Search for Bookmarks" in the side bar instead of editing properties.

![Uploading Screenshot from 2016-04-01 10:35:51.png…]()

**Comment by maggiolo00** [comment]
hi @sowmyav82 

which version?

**Comment by sowmyav82** [comment]
Hi Enrico,

2.1.13. It fixed itself yesterday. I did try restarting the server before I
reported it.

Thanks,
Sowmya

This email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by maggiolo00** [comment]
@sowmyav82 

can i close this?

**Comment by sowmyav82** [comment]
Yes. Thanks.
