### ISSUE TITLE
Use backticks in all Studio-generated queries

### ISSUE THREAD

**Issue by luinav** [orientechnologies/orientdb-studio#366]
I have successfully created a class called "IP-DMZ-INET" which is a subclass of vertex V. I have added a record without any problem.
But when I hit the buttong "Query All" of this class from the Orientdb Studio -> Schema 
I get the following error "com.orienttechnologies.orient.core.sql.OcommandSQLParsingException: Error on parsing command at position #0: Error parsing query: select \* from IP-DMZ-INET Encountered " "-" "-"" at line 1, column 17. Was expecting one of: <EOF> <WHERE> ... <ORDER> []"

The same error occurs when I write "select from IP-DMZ-INET" in the browse tab.

I am using oriendb-community-2.1.15

**Comment by maggiolo00** [comment]
hi @luinav 



you should use backtick in Browse tab.

```SQL
select from `IP-DMZ-INET`
```

I will fix the studio part to use backtick in Query All

**Comment by luinav** [comment]
I can confirm that it is ok if I use backticks.

Thank you for your quick support

**Comment by santo-it** [comment]
Thanks for submitting this. Verified as described

All queries sent by Studio should use `, not only the "query all". Other commands, including create and drop are failing

Thanks,

**Comment by maggiolo00** [comment]
Databases created with ODB < 2.1 don't support back tick. 
I will remove usage of back for those dbs

**Comment by maggiolo00** [comment]
@santo-it 
Implemented

**Comment by santo-it** [comment]
thanks. made a quick test. seems okay. closing. thanks again
