### ISSUE TITLE
Studio Cannot Choose Super Class in Scheme

### ISSUE THREAD

**Issue by t-boom** [orientechnologies/orientdb-studio#373]
I'm following the Udemy getting started course. In lecture 16, after creating the new database, I go to the Schema tab to add the Transaction class. However, when I click on New Class, the window that pops up does not allow me to select a super class.

![nosuper](https://cloud.githubusercontent.com/assets/1735659/15444148/fc2434ae-1eaa-11e6-8c03-cdf7a51b957c.png)

**Comment by maggiolo00** [comment]
@t-boom 

which version?

**Comment by t-boom** [comment]
2.2.0

I just downloaded it yesterday.

**Comment by t-boom** [comment]
That was on a Windows 10 box. It works fine on my Ubuntu 14.04 box

**Comment by maggiolo00** [comment]
@t-boom 

on my Mac box works fine. 
The QA was done on Windows also. I will check in

**Comment by maggiolo00** [comment]
@t-boom 
btw that version of the Screenshot is not 2.2 is 2.1.x if i see well.

**Comment by maggiolo00** [comment]
Maybe you did run 2.1.x and then 2.2.0?
In that case refresh your browser

**Comment by t-boom** [comment]
That's how 2.2.0 looks on my Ubuntu box. It's a fresh install this morning (I've never had OrientDB on it before).

Is there a visual difference I should look for?

**Comment by maggiolo00** [comment]
I see Profiler and Auditing tab that in 2.2.0 are not there anymore.
That is why i told you that the screenshot seems 2.1.x

**Comment by t-boom** [comment]
I tried refreshing the browser and clearing the cache, but that didn't do it. I then deleted OrientDB and re-downloaded it, and it now works no problem (and those tabs are no longer present).

I'm not sure what the problem was, but it's working now, so I'll close the issue. Thanks for the help.
