### ISSUE TITLE
Support multiple fields for display label in graph view

### ISSUE THREAD

**Issue by martinpengellyphillips** [orientechnologies/orientdb-studio#374]
Would be useful to be able to have multiple fields contribute to _Display_ label in graph view so that it is easier to distinguish nodes. For a simple example consider 'first_name', 'last_name' of a Person.

Ideal would be a format string with which we can specify the fields such as `"{first_name} {last_name}"`.

**Comment by santo-it** [comment]
Hi @martinpengellyphillips ,

Many thanks for this Enhancement Request. I agree it's something useful

**Comment by santo-it** [comment]
@maggiolo00 , this is actually quite important for the new demo db / tutorial

please could you estimate implementation cost. If we can implement it quickly let's do it, it will help us a lot in displaying queries like the following

from the 3.0 demo db (big datatest version):

Find the top 3 nationalities of the tourists that eaten at Restaurant with Id 13

SELECT Name, count(*) as CountryCount FROM (SELECT expand(out('IsFromCountry')) AS countries FROM ( SELECT expand(in("HasEaten")) AS customers FROM Restaurants WHERE Id='13' UNWIND customers) unwind countries) GROUP BY Name ORDER BY CountryCount DESC LIMIT 3

![enrico_graph1](https://cloud.githubusercontent.com/assets/14923389/23325497/15fc627a-faf6-11e6-9699-27196253a9b9.PNG)

What I would like to show: Name + CountryCount

Thanks,

**Comment by maggiolo00** [comment]
Implemented
