### ISSUE TITLE
Query Is not processing

### ISSUE THREAD

**Issue by Saharsheikh** [orientechnologies/orientdb-studio#378]
I have imported dataset of drwho and while processing this query select \* from V, it is executing fine but not producing result. infact no other query apart from this is displaying result. Though there is no error. Moreover same queries are working fine for Greatfuldeadconcert database but not for drwho.

**Comment by luigidellaquila** [comment]
Hi @Saharsheikh 

How did you import drwho database?

Thanks

Luigi

**Comment by maggiolo00** [comment]
@Saharsheikh 

Di you have any updates?

**Comment by maggiolo00** [comment]
@Saharsheikh 

i'm closing this. Please reopen if it's not resolved
Thanks
