### ISSUE TITLE
LINK to an external ressource (file, database or over orient graph)

### ISSUE THREAD

**Issue by Pamac** [orientechnologies/orientdb-studio#386]
Hello,
In a use case, the leafs of my graph are filenames. It would be usefull to have an HYPERLINK Vertex type, visible on the graph as a clickable link that open this file in a blank target or download it.

Do you have existing solutions to do that ?

Extending this use case, and using a virtual or external Vertex type, it would be nice to have an ORIENT_LINK to join an over graph by configuring the @graph an the @id or a MYSQL_LINK by confugiring @database, @table, @id.

!!! Allez les bleus !!!

Pamac.

**Comment by lvca** [comment]
Not relevant, closing it.
