### ISSUE TITLE
Configuration on Graph Not Saved

### ISSUE THREAD

**Issue by migpics** [orientechnologies/orientdb-studio#387]
I'm running Studio version : 2.1

OrientDB version : 2.1.3 and when I save the configuration and come back to the page and run "select from V" my configuration is back to the original default configuration.
Any tips on how to resolve this?

**Comment by maggiolo00** [comment]
hi @migpics 

did you login with root user?

try with admin

**Comment by migpics** [comment]
I logged in with root.  Just created a user called admin and tried it but still the same result.
Not getting an error when I save.

**Comment by migpics** [comment]
I just found this on issue 160 so I'll close this one out.
