### ISSUE TITLE
Can't import a public database check your connection 

### ISSUE THREAD

**Issue by daiyueweng** [orientechnologies/orientdb-studio#391]
Hi, I am running `orientdb studio` on `Windows 10 X64` and  tried to import a public database from the interface. But I got the following error message,

`An error occurred when trying to reach public databases repository. Please check your connection.`

How to resolve this issue. I do have the internet connection.

cheers

**Comment by maggiolo00** [comment]
Are you behind a proxy?

**Comment by daiyueweng** [comment]
I don't know, how to check that? And if so, what should I do. But I think I am behind firewall.

**Comment by maggiolo00** [comment]
Are you able to get this json file?

http://www.orientechnologies.com/public-databases/config.json

**Comment by daiyueweng** [comment]
Yes. I am able to open the json file in my browser.

**Comment by maggiolo00** [comment]
Which version do you have?

**Comment by daiyueweng** [comment]
I installed `Orient DB 2.2.4 Community Edition` on `Windows 10 X64`.

**Comment by maggiolo00** [comment]
which browser?

**Comment by daiyueweng** [comment]
This issue happened on both `Chrome` and `IE 11`.

**Comment by maggiolo00** [comment]
We do our QA also on Windows. And it works with Windows 8 and Chrome.

This is the code executed to fetch the json file.

If you execute this in Chrome console we can inspect which is the error.

```js
$.ajax({
      type: "GET",
      url: "http://www.orientechnologies.com/public-databases/config.json",
      crossDomain: true
    }).done(function(data){ console.log(data)}).fail(function(err){console.log(err)});
```

**Comment by daiyueweng** [comment]
execute it in `Chrome` console, got an error,

`VM91:1 Uncaught TypeError: $.ajax is not a function(…)(anonymous function) @ VM91:1`

**Comment by maggiolo00** [comment]
@daiyueweng 

sorry i forgot, you should execute it in the windows with studio opened so you have jquery installed.

**Comment by daiyueweng** [comment]
executed it in the tab with studio is opened, got the same error,

`Uncaught TypeError: $.ajax is not a function(…)(anonymous function) @ VM168:1`

**Comment by maggiolo00** [comment]
Seem strange.

We did test in Windows Environment without problem.

**Comment by daiyueweng** [comment]
have you tested it in `Windows 10 Pro X64`?

**Comment by santo-it** [comment]
Hi,

Just a quick comment to say that I am not able to repeat this issue. It seems that the "Import Public Databases" feature is working fine, at least in the following scenarios:

1.

- Windows 10 Home 32bit
- OrientDB Enterprise 2.2.8
- Chrome 53.0.2785.101m or Firefox 48.0.2

2.

- Windows 10 Home 64bit 
- OrientDB Enterprise 2.2.8
- Firefox 48.0.2 or IE 11.103

@daiyueweng: I was just wondering if perhaps you had a chance to give this another try? are you still getting the same issue?

Thanks,

**Comment by a-unite** [comment]
I had the same problem with docker image on Win10 Pro couple of days ago as well.
Symptoms were: loading in perpetual progress, even a folder created, but it was halting after few long minutes (due timeout, I guess). Nothing helped.

Then, suddenly (actually, it happened after another routine docker reinstallation), problem dissolved without any special force from my side (and it still works). Might there happen some periodical hosting problems for those databases?

**Comment by lvca** [comment]
Closing it. In case you see this problem again, please comment this.

**Comment by kami71539** [comment]
I am facing the exact same issue.
