### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by JOSHI919** [orientechnologies/orientdb-studio#392]
Hi,

I am using OrientDB version : 2.2.3 and deployed my application in public cloud server, when i hit orient server URL(IP:2480), its displaying all database name, which can be seen by any one.

To over come this issue i removed guest account from orientdb-server-config.xml file, but still its not asking for username and password which was there in previous version.

Since now my database names are open to all,please help me to overcome this issue.

**Comment by SDIPro** [comment]
Hi @JOSHI919,

Look in the config folder for security.json.  Open that and look for a "resources" property under the "Password" authenticator. You can remove the "guest" username, change its "resources" permissions, or disable the password authenticator entirely.

Let me know if that solves it for you.

**Comment by JOSHI919** [comment]
Thanks...its working
