### ISSUE TITLE
NPE when inserting record

### ISSUE THREAD

**Issue by anatse** [orientechnologies/orientdb-studio#397]
Hi. The NPE exception is thrown when I try to insert record in database  

**Schema script:**
```
create class CodeWithName;
create property CodeWithName.code string;
create property CodeWithName.name string;
alter property CodeWithName.code mandatory true;
alter property CodeWithName.name mandatory true;

create class Address;
create property Address.city embedded CodeWithName;
create property Address.street embedded CodeWithName;
create property Address.building embedded CodeWithName;
alter property Address.city mandatory true;
alter property Address.street mandatory true;
alter property Address.building mandatory true;

create class Pharmacy EXTENDS V;
create property Pharmacy.name STRING;
create property  Pharmacy.address embedded Address;
create property  Pharmacy.chiefPhone STRING;
alter property Pharmacy.name MANDATORY TRUE;
alter property Pharmacy.address MANDATORY TRUE;
```

**NullPointerException occurred when trying to execute insert** 
`insert into Pharmacy(name, address) values ('Pharmacy', {"@type":"d", "@class": "Address",  "city": {"@type":"d", "@class":"CodeWithName", "code":"1", "name": "New-York"}, "street": {"@type":"d", "@class":"CodeWithName", "code":"10", "name": "24"}, "building": {"@type":"d", "@class":"CodeWithName", "code":"100", "name": "100"}})`

**In log only**: SEVER Internal server error:
java.lang.NullPointerException [ONetworkProtocolHttpDb]

**Comment by maggiolo00** [comment]
hi @anatse 

which version of OrientDB?

**Comment by maggiolo00** [comment]
Duplicate Issue

https://github.com/orientechnologies/orientdb/issues/6597
