### ISSUE TITLE
Context Path / Reverse Proxy

### ISSUE THREAD

**Issue by chunkiat82** [orientechnologies/orientdb-studio#400]
Even though I have mapped it to studio in my ngnix conf, http://hello.com/studio/.

So the page loads right but everything else after that goes wrong.

The angular scripts still want to access http://hello.com/listDatabases, I think there should be a place where can we pass in the context path like Jenkins?

**Comment by maggiolo00** [comment]
hi @chunkiat82 

which version are you using?

**Comment by chunkiat82** [comment]
Version 2.2.9 docker image. 

~Forgive Auto Correct

**Comment by maggiolo00** [comment]
@chunkiat82 
How did you configure it ?

**Comment by chunkiat82** [comment]
standard conf @ https://gist.github.com/chunkiat82/c6102a9813aa3efa1f289da2e6c14018

nginx conf

```json
location /studio/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:2480;
        proxy_redirect default;
}
```

**Comment by maggiolo00** [comment]
This one worked for me.


```
            location /admin/ {
                proxy_pass http://localhost:2480/;
            }
```
I guess the trailing slash in proxy_pass is what makes the difference
Then
http://domain.com/admin/studio/index.html#/
And it showed me the dbs list

**Comment by maggiolo00** [comment]
@chunkiat82 

let me know if this helps you!
Thanks

**Comment by chunkiat82** [comment]
@maggiolo00 cool, it worked for me.

Actually that's the very first one i tried but it failed for some reason. So I tried those above.

Like you said the trailing slash is important.

Thanks!

**Comment by chunkiat82** [comment]
just an update, I am getting weird streaming issues like net::ERR_INCOMPLETE_CHUNKED_ENCODING

not sure if it's related to https://github.com/orientechnologies/orientdb/issues/6647

**Comment by chunkiat82** [comment]
scripts.js:83 POST http://domain.com/command/test2/sql/-/-1?format=rid,type,version,class,graph net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by maggiolo00** [comment]
@chunkiat82 

i think it's related to that issue.

can you try to disable the streaming as suggested in the issue?

Thanks

**Comment by chunkiat82** [comment]
tried, still did not work.

I will try again tomorrow with a fresh mind. 

maybe i missed something

thanks anyway
