### ISSUE TITLE
Use different logo in Studio Enterprise

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#407]
Hi,

It could be useful to have a way to easily understand, by looking at Studio, if it is the Community or Enterprise Edition

A way to achieve this could be to use a different logo in the Enterprise Edition (I'm talking about the OrientDB logo visible from the top-left corner). In the Enterprise Edition that logo could include the label "Enterprise"

Thanks,

**Comment by maggiolo00** [comment]
Hi @santo-it 

implemented it will be available in the next snapshot of OrientDB 3.0

**Comment by maggiolo00** [comment]
or 2.2.x

**Comment by santo-it** [comment]
Many thanks. Fix verified and cited in the Release Notes. Closing
