### ISSUE TITLE
Script SQL is not working in console

### ISSUE THREAD

**Issue by borov333** [orientechnologies/orientdb-studio#408]
Hi guys,

I'm running orientdb v 2.2.10
I tried to execute script on multiple lines in the console using "script sql", but it failed in the console. Same exact script executed just fine in the browser studio.

orientdb {db=Customers}> info class PresetAttribute
PROPERTIES
PROPERTIES
+----+------+------------+-----------------+---------+--------+--------+----+----+-------+-----+
|#   |NAME  |TYPE        |LINKED-TYPE/CLASS|MANDATORY|READONLY|NOT-NULL|MIN |MAX |COLLATE|DEFAULT|
+----+------+------------+-----------------+---------+--------+--------+----+----+-------+-----+
|0   |values|EMBEDDEDLIST|STRING           |false    |false   |false   |    |    |default|       |
|1   |name  |STRING      |                 |true     |false   |true    |    |    |default|       |
+----+------+------------+-----------------+---------+--------+--------+----+----+-------+-----+

orientdb {db=Customers}> script sql
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=Customers}> insert into PresetAttribute set name = 'utilityCompany', values = [
orientdb {db=Customers}>     'American Electric Power',
orientdb {db=Customers}>     'Azusa Light & Water',
orientdb {db=Customers}>     'Black Hills Energy',
orientdb {db=Customers}>     'Bryan Texas Utilities',
orientdb {db=Customers}>     'California Public Utilities Commission',
orientdb {db=Customers}>     'Central Maine Power',
orientdb {db=Customers}>     'City & County of San Francisco'
orientdb {db=Customers}>     ]
orientdb {db=Customers}> end

Error: com.orientechnologies.orient.core.exception.OSecurityException: Language 'sql insert into presetattribute set name = 'utilitycompany', values = [' is not allowed to be executed
	DB name="Customers"
	DB name="Customers"

 Maybe I'm doing something wrong? I will need to load data in few large lists, let me know if there is a better way to do this. Thanks.

**Comment by luigidellaquila** [comment]
Hi @borov333 

This issue was fixed in 2.2.11 (see https://github.com/orientechnologies/orientdb/issues/6665), that is already available for download

Thanks

Luigi

**Comment by borov333** [comment]
When I tested it in 2.2.11 I swear it was working, but now I installed 2.2.12 and it is no longer working. Please see if anything got messed up with .12 release. Here are the console statements I ran:

Working:
```
orientdb {db=Customers}> select from account where @rid = #25:0

+----+-----+-------+----+------+--------+--------+---------+---------------+----------------+-----------------+-----------------------+-----------------------+--------------------------------------+
|#   |@RID |@CLASS |id  |active|out_Sell|company |out_Emplo|website        |created         |settings         |purchaseKey            |accessKey              |address                               |
+----+-----+-------+----+------+--------+--------+---------+---------------+----------------+-----------------+-----------------------+-----------------------+--------------------------------------+
|0   |#25:0|Account|17  |true  |[#161:0]|Seller 0|[#41:0]  |http://www.s...|2016-09-22T19...|AccountSetting...|c9fc6932-68f3-4033-8...|45843fdb-aee8-4a96-8...|Address{street:1234 Sunset Dr.,city...|
+----+-----+-------+----+------+--------+--------+---------+---------------+----------------+-----------------+-----------------------+-----------------------+--------------------------------------+

1 item(s) found. Query executed in 0.003 sec(s).
```

Not Working:
```
orientdb {db=Customers}> script sql
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=Customers}> select    
orientdb {db=Customers}> from account
orientdb {db=Customers}> where @rid = #25:0
orientdb {db=Customers}> end

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalid script:Encountered " <SELECT> "select "" at line 1, column 1.
Was expecting one of:
    <IF> ...
    ";" ...
    <IF> ...
    
	DB name="Customers"
	DB name="Customers"
```

**Comment by luigidellaquila** [comment]
Hi @borov333 

sorry, my bad, the issue you are reporting here is a different one from https://github.com/orientechnologies/orientdb/issues/6665

Actually this syntax has never worked (not even in 2.2.11) and it's not planned to be supported in v 2.2.x. 
In batch scripts, every statement has to be on a single line

Thanks

Luigi
