### ISSUE TITLE
Import Database button in the Home Page

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb-studio#410]
Studio should have a new button "Import Database..." to start a wizard with Teleporter.

**Comment by santo-it** [comment]
Status: button implemented in 2.2.15 with 455c90984c6013ab8a5affb2e3876dcd3f8e2c58 and related commits. Wizard creation in progress.

Reassigning to @G4br13l3

**Comment by G4br13l3** [comment]
Teleporter wizard completed.
