### ISSUE TITLE
Serious graph editor usability and performance problems

### ISSUE THREAD

**Issue by endash** [orientechnologies/orientdb-studio#411]
I'll preface this by saying that I installed orientdb less than an hour ago. This is all from the perspective of a brand new user without any experience with the product. My methodology: I downloaded and ran the server (which, btw, was a different process than that described on the download page), then opened the Grateful Dead database and ran the query "select from V;"

The initial render looked like this:

<img width="1172" alt="screen shot 2016-11-03 at 11 57 34 am" src="https://cloud.githubusercontent.com/assets/20806/19973867/e3448d68-a1bc-11e6-8955-a0c45de6663b.png">

This is not that complex a graph, it shouldn't be so unreadable. I couldn't find any mechanism to force the graph to layout in a more sane fashion. Even a super simple graph just does not render sanely:

<img width="581" alt="screen shot 2016-11-03 at 12 03 52 pm" src="https://cloud.githubusercontent.com/assets/20806/19974082/b0c0dd96-a1bd-11e6-98b9-d0f0df812372.png">

By manually clicking and dragging nodes it is clear that there isn't anything going on with this graph that should confuse the layout algorithms:

<img width="629" alt="screen shot 2016-11-03 at 12 04 17 pm" src="https://cloud.githubusercontent.com/assets/20806/19974124/c75cb8cc-a1bd-11e6-8680-71fa17d89891.png">

Worse, though, is when I try something simple to discover the graph, like double clicking a node:

![screen shot 2016-11-03 at 11 37 26 am](https://cloud.githubusercontent.com/assets/20806/19973933/209ab5f2-a1bd-11e6-9093-2fd3c968d32f.png)

That's what it settled into after a half minute of churning through 0.1fps layout animations, at least.

**Comment by maggiolo00** [comment]
@endash 

it's clear that the GratefulDead concert is not a good example for this. In your latest screenshot you have few vertex
and a lot of connections between them and that is causing this layout. 
We use d3 with the force layout with these parameters

```
{"linkDistance":200,"charge":-1000,"friction":0.9,"gravity":0.1}
```

About performances d3 uses SVG that it's known to be slower in rendering compared to WebGL/Canvas.

If you have some tweak tips, we are open on suggestion 

Thanks

**Comment by endash** [comment]
@maggiolo00 

The GD database might not be a great example to include from a marketing perspective if using it doesn't reflect well on the software's capabilities, but it's a perfectly fine example for demonstrating these issues. It's not like I hunted down the worst dataset possible to highlight edge-case flaws in the app—it was the first thing I tried. It's actually a great example because to a certain degree it consists of the sort of highly interconnected data that I work with, so I consider it a close approximation to my real-world use case.

The last screenshot was primarily intended as a demonstration of how unintuitive the interface is, with the performance ramifications a particularly unpleasant cherry on top. I don't know why clicking on one single node resulted in hundreds of connections between unrelated nodes being added to the rendering. It's an obvious thing to try to navigate a graph that has been partially loaded or is too dense to be readable, but the results are entirely non-obvious. The performance wouldn't be an issue, probably, if it weren't randomly adding tons of connections to the graph, but even then there are simple ways to detect that there's likely to be a performance problem and then give the user a way to cancel before locking the browser up for nearly a minute. But, again, even simple graphs don't render well, and even if it were a lightly connected graph the behavior is still unexpected and less than useful.

I'm always happy to offer suggestions, tweaks, and even complete pull requests, but if I'm the only one that sees these things as actual problems it doesn't seem like it'd be helpful. I don't think I'm picking nits or being unfair, or particularly obtuse.

**Comment by endash** [comment]
I'm actually going to put a hold on this while I go through the studio app more closely, because I'm noting some other things that could use usability tweaks (like date entry, for instance, which doesn't allow ISO8601 format, and instead requires little-endian dates.) I'd rather collect all the things I find in one place with an action plan rather than debate whether something's actually a problem item-by-item.

**Comment by maggiolo00** [comment]
@endash 

thanks, i say you can collect them in a new issue. I will mark this as  enhancement since there is some improvement that we can do to the graph rendering but considering that with SVG 
is not performant in such task.

**Comment by santo-it** [comment]
Hi @endash,

Thank you very much for trying OrientDB and for investing some time to send your feedback. That's really appreciated

I just wanted to add a quick comment to say that we also believe that the GratefulDeadConcerts database is not the best example database. For this reason we have recently created an issue: https://github.com/orientechnologies/orientdb/issues/6905

Just wondering: have you tried with importing the "Beer" Database? I think it might help you with your OrientDB learning. You can import that database directly from the Studio Home Page (click on that "import a public database" button)

Thanks for your feedback about our download page. I guess you are referring to the fact that it does not cite to start the server using ./server.sh or server.bat (?).  I talked to our webmaster already and he told me he will improve the page

Thanks,

**Comment by santo-it** [comment]
Hi @endash, 

Just a quick note to say that we have improved our download page: http://orientdb.com/download/

We hope that it's more clear now. Feel free to let us know if you have any additional feedback on this (download) topic

Thanks,

**Comment by lvca** [comment]
We provide in v3.0 a different database to show the multi-model features.
