### ISSUE TITLE
Wrong links to doc

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#427]
Hi,

Listing below a set of doc links that are wrong

- add new record (vertex) http://orientdb.com/docs/2.2/Edit-vertex.html - the correct one is http://orientdb.com/docs/2.2.x/Edit-Vertex.html

- add new record (document) http://orientdb.com/docs/2.2/Edit-document.html - the correct one is http://orientdb.com/docs/2.2.x/Edit-Document.html

- edit class: http://www.orientdb.com/docs/2.2/Schema.html#property - the correct one is http://orientdb.com/docs/2.2/Schema.html#properties

Please, let's wait a bit before implementing this - let's identify all broken links first, coordinate with doc team and then implement this (doc links may change)

**Comment by maggiolo00** [comment]
Fixed
