### ISSUE TITLE
rendering - 2 vertices and 3 edges

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#428]
Hi,

Please check image below:

![graph_editor_bug_to_be_opened](https://cloud.githubusercontent.com/assets/14923389/21602921/6fb8f62e-d199-11e6-9ac7-bbfeae6e131d.PNG)

the more the 2 vertices are distant, the more the radius of the 3rd edge increases. When the two vertices are closer, the radius is smaller and the edge looks good

to repeat, after creating the two vertices and the 3 edges try to move one vertex away from the other

Wondering if we can improve such behavior?

**Comment by maggiolo00** [comment]
Implemented
