### ISSUE TITLE
New Vertex - Issue with Create Edge

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#429]
Hi,

When creating a new record using the "new record" button, until the vertex has not been saved, the "In Edges" and "Out Edges" frames should be disabled, otherwise if the user tries to create an edge before saving the vertex an error is returned (because there's no vertex rid yet)

On new record creation, please enable those frames only if save command was successful. On edit record, this problem does not occur, as there's a rid already

Thanks,

**Comment by maggiolo00** [comment]
Fixed
