### ISSUE TITLE
"Import from Neo4j" Wizard + Button in the Home Page

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#432]
1. wizard to set the options, and import a Neo4j Database into OrientDB
2. button in the home page to open the wizard

**Comment by santo-it** [comment]
#1 now implemented

**Comment by G4br13l3** [comment]
Hi @santo-it, I'm going to refactor the server management area: we will have a single entry point in the dashboard where you can choose the specific importer you need to use (Teleporter, Neo4jImporter, OrientDBImporter, ETL in the future etc). 

Thus we will have a single button in the home page that will redirect to the dashboard. I'm closing the issue.

Thanks. 

Gabriele
