### ISSUE TITLE
Show source and target vertices when editing edges

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#435]
how to repeat

- select * from e
- click on an edge rid . edit edge window will be opened
- in and out edges frames are enabled, and if you try to use them obviously you'll get an error "Cannot retrieve a vertex with the RID #25:1 because it is an edge"

please let's consider to disable these frames while editing an edge, if this operation is not allowed by design. this will help new users

perhaps an internal check to understand if we are editing a vertex or edge, and in case disable them in this second case?

thanks

**Comment by santo-it** [comment]
@maggiolo00 hi, i'm tagging this with PBL1 as we fixed something related to this recently. makes sense we fix this as well for next release

thanks,

**Comment by santo-it** [comment]
Actually, more than disabling the in and out edges frames, we may visualize source and target vertices frames, as suggested in https://github.com/orientechnologies/orientdb/issues/1023. This would be more coherent with what we do when editing a vertex

So the frames would be:

"Source Vertex"
"Target Vertex"

Each frame would include the vertex rid (clickable --> edit vertex window)

**Comment by maggiolo00** [comment]
@santo-it  Fixed 
In case of edge From/To Vertex are shown with the links to -> edit vertex

**Comment by santo-it** [comment]
Very well done @maggiolo00 . Much better now. Thanks

Just a question: have you tried the case of new edge. With edit edge I'm not having issues, but when I try to add an edge, and then add the out and in fields, the frames are updated showing what I type in those fields. When I save the record is saved, but when I try to visualize the two vertices, the edge is not shown. Just wondering if you handled the new edge creation as well. 

I believe this is the last case of the all cases we recently reviewed (add vertex, edit vertex, edit edge)

Thanks,

**Comment by santo-it** [comment]
Closing this. Will create a new issue for the "add edge" case. Thanks.
