### ISSUE TITLE
Clear the red error bar when moving from a menu to another

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#437]
Hi,

This should be hopefully easy, and at the same time it will improve usability and product experience, especially for new users

If possible, please let's consider to clean the red error bar when moving from a menu to another. E.g.

- go in the cluster management section on a stand-alone server: message " com.orientechnologies.orient.core.exception.OConfigurationException: Seems that the server is not running in distributed mode" will appear
- move to Security or Teleporter. That error message is still present, however, it is out of context and can create confusion

- Same for the menu "browse", "schema" etc

- We should clean it even on the code that we execute when pressing some buttons like "execute" on both "browse" and "graph editor" tabs, connect and other buttons

Thanks,

**Comment by santo-it** [comment]
@maggiolo00,

Thanks! Can you clean it also in the following two other cases:

- from the "cluster management" tab, to other tab, e.g. "teleporter"
- when we execute "run query" in the graph editor (try to run a wrong query. correct that query and run it. the bar should disappear)

Thanks,

**Comment by maggiolo00** [comment]
Done
