### ISSUE TITLE
Graph Editor - Create Edge - Property is not added

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#438]
Hi,

Verified with 2.2.13, 14 and 15-latest

Graph editor. Select a vertex. Click to add an edge. When creating the edge set a property. Save. The edge is created but the property is ignored

Note that the property is created correctly when editing an existing edge

Note that after the edge is created, we may consider to refresh the edge frame on the left with the new edge (right now it display the original vertex. Not saying current approach is "wrong" but we may consider to show the info on the new edge, WDYT? in this case you'll note the original issue immediately, as the property is not there)

Thanks,

**Comment by maggiolo00** [comment]
Fixed

**Comment by santo-it** [comment]
Many thanks - documented in the [Release Notes](https://github.com/orientechnologies/orientdb/wiki/OrientDB-2.2-Release-Notes)
