### ISSUE TITLE
In the Servers Management view, you can't filter by type to see "SEVER" log entries

### ISSUE THREAD

**Issue by SamHard** [orientechnologies/orientdb-studio#446]
I was searching for errors in the logs using the Servers Management view, and I noticed entries of type SEVER, but I couldn't filter to see just those entries.  I think that type should be added to the drop-down list.
![image](https://cloud.githubusercontent.com/assets/22059555/22814737/8ec6152a-ef1b-11e6-9c23-714bd8e1d1df.png)

**Comment by maggiolo00** [comment]
hi @SamHard 

this has been fixed by this commit

https://github.com/orientechnologies/orientdb-studio/commit/b31810c8c51d42e4269209fa31332a7628c15a2f

and it's available in version 2.2.16

Thanks

**Comment by SamHard** [comment]
Okay, thanks!  I just upgraded to 2.2.16, and I see it now.  Sorry for creating an extra issue.
