### ISSUE TITLE
Schema Panel - Sometime search does not work

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#451]
highly affected as it seems this is my standard workflow

below i'll use openbeer db as example

- connect to openbeer db
- click on schema
- type bee in the search area --> it works
- copy "bee" into the clipboard
- clean the search area --> it works
- ctrl + v into the search area --> it works 
- click on graph editor
- click on schema tab
- ctrl + v into the search area --> it does not work (even pressing the search button)

**Comment by maggiolo00** [comment]
Fixed
