### ISSUE TITLE
Graph Editor - Visualization Problem when switching Schema-Graph

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#452]
under certain conditions, n--m queries are not visualized correctly

**Comment by maggiolo00** [comment]
Fixed

**Comment by santo-it** [comment]
Enrico, sorry, I am reopening this

I am still able to reproduce, even if it is not easy. Below a possible sequence:

using the new demoDb (but problem appeared also with beer db if you remember)

- traverse * from #73:0 maxdepth 2
- change color of an edge and save
- back to schema. back to graph
- back to schema. back to graph
- back to schema. back to graph
- the problem appears, see image below:

anonymous users on chrome, if it makes any difference:

![enrico2](https://cloud.githubusercontent.com/assets/14923389/23284599/9bc7d2ec-fa2c-11e6-80b9-a7d1dfe45c10.PNG)

**Comment by maggiolo00** [comment]
hi @santo-it 

this is a different issue. The previous one fired a JS error. I think this one not.
I bet if you fire again the query, it will adjust the rendering. 
It should be caused by the first rendering optimization in the first load.

**Comment by maggiolo00** [comment]
Fixed also this one
