### ISSUE TITLE
Graph Editor - Under certain conditions colors are not persistent

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#453]
- connect
- graph editor --> query that return many different vertex classes. Take screenshot so that you can see colors
- go to schema panel
- back again to graph editor --> the graph is loaded (as it should) but colors are changed

Colors should be persistent (until the user disconnects)

**Comment by maggiolo00** [comment]
hi @santo-it 
i'm not able to reproduce it. Do you have a db that reproduce this issue?

Thanks

**Comment by santo-it** [comment]
Hi,

Try this:

1. create new db
2. from browse, set batch
3. copy / paste / execute

CREATE CLASS A EXTENDS V;
CREATE PROPERTY A.id LONG;
CREATE INDEX A.id ON A(id) UNIQUE;

CREATE CLASS B EXTENDS V;
CREATE PROPERTY B.id LONG;
CREATE INDEX B.id ON B(id) UNIQUE;

CREATE CLASS C EXTENDS V;
CREATE PROPERTY C.id LONG;
CREATE INDEX C.id ON B(id) UNIQUE;

CREATE CLASS D EXTENDS V;
CREATE PROPERTY D.id LONG;
CREATE INDEX D.id ON D(id) UNIQUE;

4. click on schema tab and take screenshot

5. back to browse tab, copy / paste / execute:

CREATE VERTEX A SET id = '1';
CREATE VERTEX B SET id = '1';
CREATE VERTEX C SET id = '1';
CREATE VERTEX D SET id = '1';

CREATE CLASS AB_Edge EXTENDS E;
CREATE CLASS BC_Edge EXTENDS E;
CREATE CLASS CD_Edge EXTENDS E;

CREATE EDGE AB_Edge FROM (SELECT FROM A WHERE id = 1) TO (SELECT FROM B WHERE id = 1);
CREATE EDGE BC_Edge FROM (SELECT FROM B WHERE id = 1) TO (SELECT FROM C WHERE id = 1);
CREATE EDGE CD_Edge FROM (SELECT FROM C WHERE id = 1) TO (SELECT FROM D WHERE id = 1);

6. back to schema tab and take screenshot: see that studio is using different colors than before

7. go to graph editor and execute 

MATCH {class: A, as: a}-AB_Edge->{class: B, as: b}-BC_Edge->{class: C, as: c}-CD_Edge->{class: D, as: d} RETURN $elements;

You ll see different colors - so 3 different sets. Here are some screenshots

Set 1
![image1](https://cloud.githubusercontent.com/assets/14923389/23144151/005f7a20-f7c6-11e6-98b3-9a1f7401de5c.PNG)

Set 2
![image2](https://cloud.githubusercontent.com/assets/14923389/23144156/05fd8940-f7c6-11e6-8fd5-f34320a7803d.PNG)

Set 3
![image3](https://cloud.githubusercontent.com/assets/14923389/23144160/08c13d70-f7c6-11e6-8e43-73f023518ba7.PNG)

**Comment by maggiolo00** [comment]
Implemented
