### ISSUE TITLE
#448 spin-off: graph editor - new edge/vertex windows - additional fetch of metadata

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#454]
Spin-off of https://github.com/orientechnologies/orientdb-studio/issues/448

Say users are using both Studio and other connections to the same database (via console or application) and these other connections are creating classes: the new classes won't be showed in the graph editor if user try to add a vertex / edge.

This is an enhancement request to list of available classes every time the add vertex / edge windows are created via an additional fetch of metadata

**Comment by maggiolo00** [comment]
Implemented

**Comment by santo-it** [comment]
Tested. Release Notes were up to date already. All done here. Many thanks
