### ISSUE TITLE
Schema panel - edge classes - show stroke colors instead of fill colors

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#457]
Hi,

From the graph editor, when editing an edge, it can be set stroke color. However, when saving the color configuration, it seems that two color properties are saved for edges: stroke and fill color

one question is: what is that fill color for the edges?

regardless, can we show stroke color (and not fill color) when displaying colors for edge classes in the schema panel. for vertices and generic classes, it is okay if we keep showing fill color

this will be much more intuitive and in line with what is visualized in the graph editor (the correct stroke color that user set)

thanks,

**Comment by maggiolo00** [comment]
> one question is: what is that fill color for the edges?

Fill is ignored

> egardless, can we show stroke color (and not fill color) when displaying colors for edge classes in the schema panel. for vertices and generic classes, it is okay if we keep showing fill color

Sure

**Comment by maggiolo00** [comment]
Fixed
