### ISSUE TITLE
Graph Editor - Creating an Edge popup the V classes instead the E classes

### ISSUE THREAD

**Issue by StarCmd** [orientechnologies/orientdb-studio#465]
## Expected behavior  
When you create a new Edge between 2 vertices, the first panel should ask to choose an E classes through a drop-down menu.

## Actual behavior  
From time to time, the drop down menu is populated by V classes.

## Steps to reproduce  
Using the Graph Editor, create 2 Vertices then try to create an Edge between them.
Sometime it work, sometime it fail.

![newedge](https://cloud.githubusercontent.com/assets/27196262/24898950/e3366058-1e9e-11e7-99bc-b880c33e6cfc.png)

![newedge2](https://cloud.githubusercontent.com/assets/27196262/24898953/e5e42e66-1e9e-11e7-9c56-333a386867b0.png)

![newedge3](https://cloud.githubusercontent.com/assets/27196262/24898956/e92a9358-1e9e-11e7-811e-2afe9ce4d6c4.png)

**Comment by maggiolo00** [comment]
hi @StarCmd 

i was not able to reproduce it. 
Do you have some hint on how to reproduce it?

**Comment by StarCmd** [comment]
No,
it occurs without consistencies. I am able to reproduce it about every 10 clicks.
I try to click on different area of the destination Vertex, and more or less rapidly.
Note that I use Safari, so maybe the behavior is related to the  browser.

**Comment by maggiolo00** [comment]
hi @StarCmd 

I've fixed it. It will be available in the next Hotfix 2.2.19
Thanks
