### ISSUE TITLE
green bar displayed for an error

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#468]
should be the non-disappearing red bar

to repeat:

1. set up master + 2 slave
2. try to create new record on the slave from the browse tab

error:

{"errors":[{"code":500,"reason":500,"content":"com.orientechnologies.orient.core.exception.ODatabaseException: Cannot find best cluster for class 'V' on server 'n3' (clusterStrategy=round-robin dCfgVersion=4)\r\n\tDB name=\"luca2\""}]}

Which command is the one that produces the above?

I was expecting something like

com.orientechnologies.orient.server.distributed.impl.OWriteOperationNotPermittedException: Cannot execute write operation (...) on node 'n2' because is non a master

**Comment by maggiolo00** [comment]
Hi @santo-it 

That is probably a bug in the http protocol error handling, Let me check

**Comment by maggiolo00** [comment]
Fixed and added in release notes
