### ISSUE TITLE
Performing a select in the Graph Editor has a cumulative effect

### ISSUE THREAD

**Issue by maseev** [orientechnologies/orientdb-studio#470]
Here's the problem. When I run the following query I get the graph that looks like this:
![selection_001](https://cloud.githubusercontent.com/assets/3434800/26027616/068f919a-383b-11e7-9271-8601fa797586.png)

When I run the second query I got this 'cumulative effect' so to speak:
![selection_002](https://cloud.githubusercontent.com/assets/3434800/26027617/0690df8c-383b-11e7-8ac4-c65730287c46.png)

I know this because when I reload the page (hit Ctrl+R) and run the same query again, I get the following result:
![selection_003](https://cloud.githubusercontent.com/assets/3434800/26027615/065984c4-383b-11e7-86a3-c0984a1a9756.png)

I'm not sure this is an expected behavior.

**Comment by maggiolo00** [comment]
Hi @maseev 

this is the expected behavior. 
The Graph Editor is cumulative for each query. If you want to start with a fresh Graph Editor

you can click the clear canvas button (trash icon)

Thanks
Enrico

**Comment by maseev** [comment]
@maggiolo00 Well, this is a very interesting solution indeed. Thanks for clarifying!
