### ISSUE TITLE
webpack: Failed to compile. Path must be a string.

### ISSUE THREAD

**Issue by gohilronak** [orientechnologies/orientdb-studio#472]
Dear Sir,

I have followed steps of README.md file.
But `npm run watch` gives following error:

> ERROR in Path must be a string. Received undefined
> webpack: Failed to compile.

Versions:
node: 7.3.0
npm: 4.2.0
OS: Windows 8.1

Please guide, 
Thank you...

**Comment by maggiolo00** [comment]
hi @gohilronak 

i'm still investigating that issue.  Working with node < 6 solve this issue

**Comment by gohilronak** [comment]
Thank you @maggiolo00 for quick reply
Let me try with node 6.10.3-x64.

**Comment by gohilronak** [comment]
Sir,
With `Node: 5.12.0`, and `npm: 2.15.12`.
`npm run watch` gives following message:
> webpack: Compiled with warnings.

When I open `http://localhost:8080`, I see blank page.
In console I am getting following error message:
> Cannot resolve all parameters for 'Parser'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Parser' is decorated with Injectable.

Can you please suggest me exact Node and npm version to use?
Thank you...

**Comment by maggiolo00** [comment]
Hi @gohilronak 

did you try my hint on email with

```
yarn install 
```

Thanks

**Comment by gohilronak** [comment]
Yes sir, after `yarn install` it is not showing any error in command line.

When I open http://localhost:8080, I see blank page.
In console I am getting following error message:

> Uncaught Error: Template parse errors:
> Unexpected closing tag "button" ("<div class=\"col-md-2\">\r\n      <button class=\"btn\" (click)=\"exportDatabase()\">Export Database[ERROR ->]</button>\r\n    </div>\r\n    <div class=\"col-md-8\">\r\n      OrientDB Server exports the database"): ImportExport@1:176

These lines looks ok in file [import.export.component.html](https://github.com/orientechnologies/orientdb-studio/blob/master/src/app/dbconfiguration/importexport/import.export.component.html#L4).

Versions: `node: 5.12.0`, `npm: 2.15.12`

Please help me solve this error.
Thank you..

PS: Thank you sir for sending me email, but somehow I haven't received email. My email id is: gohilronak1@gmail.com . Thank you..

**Comment by maggiolo00** [comment]
hi @gohilronak 

did you try with the branch `2.2.x` ?

**Comment by gohilronak** [comment]
Thank you Sir,
Branch 2.2.10 is working fine with following commands:
```bash
$ sudo npm install -g yo bower compass yarn
$ npm install
$ bower install
$ yarn install

$ grunt server
```

I am facing  problem only in Graph Editor page.
When I fire simple query like: `select * from E` it is alerting with following error 
>com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.{"command":"select * from E","mode":"graph"}

The same query runs fine in Browse page and in Orientdb Studio packaged with database.

Versions:
>node: 5.12.0
>npm: 4.6.1
>Orientdb Database: 2.1.0-Community
>Orientdb Studio: 2.2.10 tag


I can try to solve error with different version of Orientdb Database in 2-3 days.

Thank you..

**Comment by maggiolo00** [comment]
Hi @gohilronak 

i've fixed compilation problem with node > 5

Thanks
