### ISSUE TITLE
DB creation - possible improvements

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#473]
Ref issue https://github.com/orientechnologies/orientdb-studio/issues/471

When a DB is created, then it is automatically opened using the system user that has been used to create the db (e.g. root)

It may be useful to have a check "connect after database creation using user username-here-taken-from-the text area" checked by default

This would give the possibility to un-check it if that behavior is not wanted and immediately connect after db creation using a different user, using the standard login dialog

Just some more flexibility

**Comment by maggiolo00** [comment]
hi @santo-it 

why is this related to https://github.com/orientechnologies/orientdb-studio/issues/471 ?

**Comment by lvca** [comment]
Not relevant, closing it.
