### ISSUE TITLE
Enable Gzip compression on Studio

### ISSUE THREAD

**Issue by mindnuts** [orientechnologies/orientdb-studio#476]
Hi, would it be possible to have Gzip / Deflate compression enabled for the studio plugin? Currently it take lot of time to load and with some amount of network Jitter it takes forever to load.

![image](https://user-images.githubusercontent.com/8411896/27421457-231296ec-5748-11e7-8d6d-aa0aba85d791.png)

Thanks

**Comment by maggiolo00** [comment]
Implemented 2.2.x / develop
