### ISSUE TITLE
graph editor selected even if browse editor is visualized

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#485]
hi,

not always reproducible, but i see it often

please try if you can reproduce it with this db: [graphdb_nodes_only_label_case_test_constraints2.zip](https://github.com/orientechnologies/orientdb-studio/files/1193790/graphdb_nodes_only_label_case_test_constraints2.zip)

thanks

**Comment by maggiolo00** [comment]
Fixed
