### ISSUE TITLE
order the databases are populated into the combo-box

### ISSUE THREAD

**Issue by santo-it** [orientechnologies/orientdb-studio#486]
hi,

alphabetic order could be considered - or what is the current order right now?

![enrico](https://user-images.githubusercontent.com/14923389/28874207-22142a4e-7791-11e7-97cb-4804e2cbce2c.PNG)

thanks,

**Comment by maggiolo00** [comment]
hi @santo-it 

now the order is not changed client side. Depends on the API `/listDatabase`

Alphabetic is ok for me

**Comment by lvca** [comment]
Implemented.
