### ISSUE TITLE
OrientDB allowing access to an encrypted database with the different encryption keys.

### ISSUE THREAD

**Issue by usamakhanzada** [orientechnologies/orientdb-studio#491]
OrientDB allowing access to an encrypted database with the different encryption keys.

Steps to reproduce -- [community edition 2.2.24 running on windows 10] 

```
------- create database with key1 ------
config set storage.encryptionKey Ohjojiegahv3tachah9eib==
create database remote:localhost/databases/encrypted-db root 12345 plocal document -encryption=aes

CREATE CLASS Customer 
CREATE PROPERTY Customer.id integer 
CREATE PROPERTY Customer.name String 
CREATE PROPERTY Customer.age integer

INSERT INTO Customer (id, name, age) VALUES (01,'satish', 25) 
INSERT INTO Customer SET id = 02, name = 'krishna', age = 26 
INSERT INTO Customer CONTENT {"id": "03", "name": "kiran", "age": "29"}
INSERT INTO Customer (id, name, age) VALUES (04,'javeed', 21), (05,'raja', 29) 

SELECT FROM Customer

disconnect

------- open encrypted database with key2 (different from key1) ------
config set storage.encryptionKey Ohj11iegahv3tac1111111==
CONNECT remote:localhost/databases/encrypted-db root 12345
```

Still, it is allowing connection and view the content of the customer CLASS.

**Comment by tglman** [comment]
hi @usamakhanzada,

The encryption key it need to set on the server and after the database can be open by any client with a normal user/password authentication, the encryption is just for not keep plain data on the disc, for network encryption you should use ssl and for authorizations you should use users, the encryption key set on a client is ignored.

Regards

**Comment by Johan-Tornborg** [comment]
Documentation is not correct... It refers to the config set command. Misleading the reader to believe that you have to supply encryption key.

Please note it will not matter what encryption key you pass with the command. It will open any way. It seems that documentation assumes that encryption key has to be supplied. This is not correct.

"You can access an encrypted database through either the console or the Java API. To do so through the console, set the encryption key with storage.encryptionKey then open the database".

orientdb> CONFIG SET storage.encryptionKey T1JJRU5UREJfSVNfQ09PTA==
orientdb> CONNECT plocal:/tmp/db/encrypted-db admin my_admin_password
