### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to com.orientechnologies.orient.core.db.record.OIdentifiable 

### ISSUE THREAD

**Issue by User124125** [orientechnologies/orientdb-studio#505]
OrientDB Version: v2.2.31
Java Version: version8 update45 (Build 1.8.0_45-b15)
OS: WIN10 64bit
Expected behavior

after executing the query in the bottom the graph view should continue beeing able to show "select * from Konto"
Actual behavior

after executing the query in the bottom the graph view in orientdb studio throws the error in the title when quering "select * from Konto"
Steps to reproduce

SCHEMA---------------------
vertex Konto
every: STRING, mandatory, not null
incby:DOUBLE, mandatory, not null
kontostand:DOUBLE, mandatory, not null
lastUpdated:DOUBLE, mandatory, not null
name: STRING, mandatory, not null
showDetails:BOOLEAN, mandatory, not null
vertexyEdge:STRING, mandatory, not null

edge listSuccesor
vertexEdge:STRING, mandatory, not null

---query------------------------
db.query(
"UPDATE #26:1 SET kontostand = 100, name = 'Freuden des Lebens', every = 'month', incby = 100, showDetails = false, vertexEdge = 'vertex', in_listSuccessor = ['#61:0'], out_listSuccessor = ['#62:0'], lastUpdated = '2018-02-02T05:31:24.584Z'"
)

**Comment by luigidellaquila** [comment]
Hi @AlexPGithub 

You are defining out_* in_* fields as lists of strings (instead of RIDs), try to remove the quotes and it should work fine.

As a general suggestion, you should avoid to manipulate graph properties (ie. edge pointers) at document level. It's much better for you to let OrientDB manipulate them with graph operators (create/delete vertex)

Thanks

Luigi

**Comment by User124125** [comment]
Okay thank you for helping, what i find weired though is that i dont get an error when making this query,
i expect orientdb to tell me sry this is not the correct format/type, please use format "xyyyx".
in this query i was even able to do showDetails = 'false' eventough showDetails is a boolean. So again I think this is a very rudimentary feature to be implemented, because this can break the whole Dataset very easily. I mean i get an error, its the error in the title, but this error comes to late, it came when it was to late and my vertex was messed up badly :D

**Comment by luigidellaquila** [comment]
Hi @AlexPGithub 

The problem here is that the db is schemaless, so at the document level what you do is allowed.
The exception happens at graph API level (a higher level)

Thanks

Luigi

**Comment by User124125** [comment]
Ok :) good to know. In orientdb studio i can define a schema. Is there a way to enforce this schema when making a javascript db.query() call from nodejs ?

**Comment by luigidellaquila** [comment]
Hi @AlexPGithub 

As long as you enforce a schema in the DB, all the APIs will use it for validation, so also the nodejs one

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @AlexPGithub 

Do you still need help on this issue? Can we close it?

Thanks

Luigi
