### ISSUE TITLE
Security Manager->Roles->Add Role -- Does not allow adding a Role without inheriting one of the existing Roles

### ISSUE THREAD

**Issue by bishnu-infosys** [orientechnologies/orientdb-studio#506]
While trying a create a new Role through Security Manager, it doesn't allow to create a role without inheriting an existing Role i.e. In short all the 3 fields are mandatory for creating a new Role. However while trying to create a Role through command line allows to create a role without inheriting any existing Role.
The following works and gets reflected under the security manager once created.
**insert into ORole set name="newRole", mode = 0;**
Steps to reproduce:
1. Login to orientDB as admin
2. Click on security tab, then click on Role tab, then ADD ROLE

![capture](https://user-images.githubusercontent.com/24267169/37079588-2364802e-2209-11e8-94f2-c988ac03bfda.PNG)

Thanks,
Bishnu

**Comment by wolf4ood** [comment]
Hi @bishnu-infosys 

thanks for opening this issue. i've just pushed a fix in 2.2.x and 3.0.x branch.

It will be available in the next releases.

**Comment by bishnu-infosys** [comment]
Hi @maggiolo00 ,

Thanks for your prompt response.
