### ISSUE TITLE
Unable to insert data from studio

### ISSUE THREAD

**Issue by soutlan** [orientechnologies/orientdb-studio#507]
Hello!
I have installed OrientDB_3.0.0RC2 on Windows10 and that's what happened when I tried to insert data.
Seems like the same issue as here https://github.com/orientechnologies/orientdb/issues/7898

![image](https://user-images.githubusercontent.com/12484269/37228709-2fe56ca4-23ea-11e8-90c8-2c1381ce74b1.png)

**Comment by wolf4ood** [comment]
Hi @soutlan 

i see that you type the statement 

```
insert into Template set(name = 'foo')
```

the correct one is

```
insert into Template set name = 'foo'
```

without bracket

Hope it helps

Thanks

**Comment by soutlan** [comment]
Thanks!
