### ISSUE TITLE
ZoneAwareError Module not found: Error: Can't resolve './\""'

### ISSUE THREAD

**Issue by cjl-df** [orientechnologies/orientdb-studio#508]
hello,
i got this question on windows system.

should i Start OrientDB server.

![default](https://user-images.githubusercontent.com/3387329/38482052-48f7c29a-3c00-11e8-97e5-c86422bb3923.png)

**Comment by wolf4ood** [comment]
Hi @cjl-df 

how did you start studio?

**Comment by cjl-df** [comment]
with  windows system
i just step-by-step according to read me.
and no do step 4
and the page just like this,only have a button:
![default](https://user-images.githubusercontent.com/3387329/38532791-006312f6-3ca9-11e8-86a9-4c8872301fd1.png)

**Comment by cjl-df** [comment]
1.with linux system it works very well.
