### ISSUE TITLE
Cannot modify vertex through studio

### ISSUE THREAD

**Issue by domguard** [orientechnologies/orientdb-studio#521]
Hello
Just installed OrientDB 3.0.15 GA Community Edition on macOS Mojave using Docker.
Here's all what I've done so far , under the "root" user :
- created a test db (graph)
- created two classes
- added two instances of my classes

Now, if it try to modify any vertex in Studio graph editor I get (via XHR, looked in firefox network inspector) : "com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #14:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v2) name="Test" Error Code="3"

There is no other user, and if the version is not the latest, why Studio would show it to me and allow me to edit it ?

It's also impossible to save the colors config in the schema tab. The POST issues a 200 OK response, but when coming back it's never saved.

thank you for your help, I'd love to be able to use using OrientDB

**Comment by domguard** [comment]
Reconnecting through admin seems to solve the issue
But why does the vertices created under root have disappeared ? Is there a db for each user ?

**Comment by wolf4ood** [comment]
Hi @domguard 

root i a server user and it does now work well with custom colors. Meanwhile `admin` is a database user stored inside the database, which make it possible to associate configuration to it.

**Comment by domguard** [comment]
thanks!
