### ISSUE TITLE
can we adjust the session timout duration?

### ISSUE THREAD

**Issue by tolgaulas** [orientechnologies/orientdb-studio#529]
I like to increase the session timeout duration, is it possible through config files etc?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @tolgaulas 

Studio uses OrientDB REST API, you can configure the server with a different timeout, see https://orientdb.com/docs/3.0.x/misc/OrientDB-REST.html#authentication-and-security

Thanks

Luigi

**Comment by tolgaulas** [comment]
Thanks @luigidellaquila. There are so many time out and I am guessing its network.http.sessionExpireTimeout and the command as instructed in the link document 

http://server:port/server/configuration.network.http.sessionExpireTimeout/1800

gives the below error:
```
{
  "errors": [
    {
      "reason": 405,
      "code": 405,
      "content": "Command not found: server/configuration.network.http.sessionExpireTimeout/900"
    }
  ]
}

```

**Comment by tolgaulas** [comment]
By the way I've just noticed, the network.http.sessionExpireTimout's canChange value is false..

**Comment by luigidellaquila** [comment]
hi @tolgaulas 

Try to set it on startup, adding the following to the command line:

```
-Dnetwork.http.sessionExpireTimeout=1800
```

This should do the trick

Thanks

Luigi

**Comment by tolgaulas** [comment]
Yes, it works! :) 

Thank you very much @luigidellaquila
